#!/usr/bin/env python3
"""Generate personalized outreach emails for creator master list."""

import csv
import json
from pathlib import Path

CREATORS = [
    {"name": "Bro Code", "link": "https://www.youtube.com/@BroCodez", "niche": "Coding & Software Engineering", "hook": "your Java and software engineering tutorials that break complex topics down for beginners", "product": "an AI-powered coding assistant that helps learners debug and understand Java concepts faster"},
    {"name": "Two Minute Papers", "link": "https://www.youtube.com/@TwoMinutePapers", "niche": "AI Research Summaries", "hook": "how you distill cutting-edge AI research papers into accessible two-minute breakdowns", "product": "an AI research discovery platform that surfaces the latest papers and generates plain-English summaries for researchers and enthusiasts"},
    {"name": "The Coding Train", "link": "https://www.youtube.com/@TheCodingTrain", "niche": "Creative Coding & JS", "hook": "your creative coding challenges and p5.js projects that make programming feel like art", "product": "an AI creative coding companion that helps viewers experiment with generative art and JavaScript faster"},
    {"name": "Corey Schafer", "link": "https://www.youtube.com/@coreyms", "niche": "Python & Software Dev", "hook": "your deep-dive Python tutorials on Django, Flask, and real-world software development", "product": "an AI Python tutor chatbot that gives learners instant help while following along with your tutorials"},
    {"name": "Sentdex", "link": "https://www.youtube.com/@sentdex", "niche": "Machine Learning & Python", "hook": "your hands-on Python and machine learning projects from finance to robotics", "product": "an AI/ML experimentation platform that lets developers prototype models and chat with their datasets"},
    {"name": "Amigoscode", "link": "https://www.youtube.com/@amigoscode", "niche": "Backend Systems & AI Microservices", "hook": "your backend engineering and AI microservices content for developers building production systems", "product": "an AI agent platform for deploying production-ready chatbot and microservice backends"},
    {"name": "Siraj Raval", "link": "https://www.youtube.com/@sirajraval", "niche": "AI & Machine Learning", "hook": "your energetic AI and machine learning tutorials that get people excited to build with ML", "product": "an all-in-one AI builder toolkit for creating chatbots, agents, and ML-powered apps without heavy setup"},
    {"name": "Coding with Lewis", "link": "https://www.youtube.com/@CodingWithLewis", "niche": "Software Engineering Lifestyle", "hook": "your honest software engineering lifestyle content and day-in-the-life perspective on tech careers", "product": "an AI productivity assistant built for developers who want to ship faster and stay organized"},
    {"name": "Low Level Learning", "link": "https://www.youtube.com/@LowLevelLearning", "niche": "Systems Programming & C", "hook": "your systems programming deep dives and C language content that goes beneath the abstractions", "product": "an AI coding assistant optimized for low-level and systems programming workflows"},
    {"name": "The Primeagen", "link": "https://www.youtube.com/@ThePrimeagen", "niche": "Dev Tools & Code Architecture", "hook": "your hot takes on developer tooling, Vim, and building better software architecture", "product": "a next-gen AI dev tool that integrates directly into developer workflows and speeds up code review and refactoring"},
    {"name": "Caleb Curry", "link": "https://www.youtube.com/@CalebCurry", "niche": "Beginner Programming", "hook": "your structured beginner programming courses that make fundamentals approachable", "product": "an AI tutoring chatbot designed for programming beginners who need instant answers while learning"},
    {"name": "CodingEntrepreneurs", "link": "https://www.youtube.com/@CodingEntrepreneurs", "niche": "AI Product Dev & Django", "hook": "your Django and AI product development tutorials for builders launching real SaaS products", "product": "an AI SaaS starter kit with built-in chatbot and agent features for indie founders"},
    {"name": "Wes Roth", "link": "https://www.youtube.com/@WesRoth", "niche": "AI News & Agentic Workflows", "hook": "your daily AI news coverage and breakdowns of agentic AI workflows shaping the industry", "product": "an AI agent platform launching new autonomous workflow tools your audience would want to see first"},
    {"name": "Mike Dane", "link": "https://www.youtube.com/@MikeDane", "niche": "Fundamentals of Coding", "hook": "your clear, fundamentals-first coding tutorials that help new developers build a solid foundation", "product": "an AI learning companion that reinforces coding fundamentals through interactive chat-based practice"},
    {"name": "Riley Brown", "link": "https://www.youtube.com/@rileybrownai", "niche": "Vibe Coding & AI Agents", "hook": "your vibe coding content and practical AI agent builds that show what's possible without traditional coding", "product": "a no-code AI agent builder that lets creators and founders launch chatbot-powered products in minutes"},
    {"name": "AI Explained", "link": "https://www.youtube.com/@AIExplained", "niche": "AI News & Capabilities", "hook": "your thoughtful breakdowns of AI capabilities, limitations, and what the latest models actually mean", "product": "an AI platform with transparent model capabilities your audience would appreciate an honest review of"},
    {"name": "Yannic Kilcher", "link": "https://www.youtube.com/@YannicKilcher", "niche": "Deep Learning & ML Research", "hook": "your in-depth paper reviews and technical deep dives into deep learning research", "product": "an AI research assistant that helps ML practitioners explore papers, reproduce results, and discuss findings"},
    {"name": "Skill Leap AI", "link": "https://www.youtube.com/@SkillLeapAI", "niche": "AI Tools & Workflows", "hook": "your practical AI tools and workflow tutorials that help people actually use AI in their daily work", "product": "an AI workflow automation suite with chatbot integrations your audience could adopt immediately"},
    {"name": "AI Foundations", "link": "https://www.youtube.com/@AIFoundations", "niche": "AI Agents & Vibe Coding", "hook": "your AI agent tutorials and vibe coding walkthroughs for builders getting started with autonomous AI", "product": "an AI agent framework with pre-built templates for customer support, sales, and productivity chatbots"},
    {"name": "Greg Kamradt", "link": "https://www.youtube.com/@GregKamradt", "niche": "LLMs & AI Data Pipelines", "hook": "your LLM experiments and AI data pipeline content that pushes the boundaries of what language models can do", "product": "an LLM-powered data pipeline tool with a conversational interface for querying and transforming datasets"},
    {"name": "3Blue1Brown", "link": "https://www.youtube.com/@3blue1brown", "niche": "Math & AI Foundations", "hook": "your visually stunning math explanations that build the intuition behind machine learning and neural networks", "product": "an AI math tutor that uses visual, step-by-step explanations inspired by the way you teach complex concepts"},
    {"name": "Lex Fridman", "link": "https://www.youtube.com/@lexfridman", "niche": "AI Interviews & Tech Podcasts", "hook": "your long-form conversations with AI researchers and tech leaders shaping the future", "product": "an AI conversation platform with advanced dialogue capabilities relevant to your audience of AI thinkers"},
    {"name": "Andrej Karpathy", "link": "https://www.youtube.com/@AndrejKarpathy", "niche": "Deep Learning & Neural Networks", "hook": "your neural network from scratch series and deep learning education that sets the standard for technical clarity", "product": "an AI developer platform focused on making neural network experimentation more accessible to builders"},
    {"name": "Theo - t3.gg", "link": "https://www.youtube.com/@t3dotgg", "niche": "Web Dev & Tech Architecture", "hook": "your opinionated takes on web dev stacks, TypeScript, and modern tech architecture", "product": "an AI-powered full-stack dev tool with chatbot integrations that fits the modern JS ecosystem you cover"},
    {"name": "NetworkChuck", "link": "https://www.youtube.com/@NetworkChuck", "niche": "IT, Networks & Cloud", "hook": "your high-energy IT, networking, and cloud tutorials that make complex infrastructure fun to learn", "product": "an AI IT assistant chatbot that helps sysadmins troubleshoot networks and cloud deployments faster"},
    {"name": "StatQuest", "link": "https://www.youtube.com/@statquest", "niche": "Machine Learning & Statistics", "hook": "your StatQuest approach to making statistics and machine learning concepts crystal clear", "product": "an AI statistics tutor that explains ML concepts in plain language, the way your audience already loves learning"},
    {"name": "Kevin Powell", "link": "https://www.youtube.com/@Kepowob", "niche": "Frontend CSS & HTML", "hook": "your CSS and modern frontend tutorials that help developers write better, more maintainable styles", "product": "an AI frontend assistant that generates and debugs CSS/HTML with conversational feedback"},
    {"name": "Ben Eater", "link": "https://www.youtube.com/@BenEater", "niche": "Hardware & Computing Architecture", "hook": "your breadboard computer builds and hardware tutorials that explain computing from the ground up", "product": "an AI-powered hardware documentation chatbot that helps makers troubleshoot electronics projects"},
    {"name": "Dave Farley", "link": "https://www.youtube.com/@ContinuousDelivery", "niche": "DevOps & System Architecture", "hook": "your continuous delivery and software engineering excellence content for professional dev teams", "product": "an AI DevOps assistant that integrates into CI/CD pipelines and answers infrastructure questions via chatbot"},
    {"name": "Steve Huynh", "link": "https://www.youtube.com/@ALifeEngineered", "niche": "Big Tech Careers & Software", "hook": "your big tech career insights and software engineering advice from someone who's been in the room", "product": "an AI career coaching chatbot that helps developers prepare for interviews and level up their skills"},
    {"name": "AI Advantage", "link": "https://www.youtube.com/@aiadvantage", "niche": "AI Productivity & Prompting", "hook": "your AI productivity tips and prompt engineering tutorials for getting real results from AI tools", "product": "an AI productivity suite with advanced prompting and custom chatbot workflows for power users"},
    {"name": "Jack Herrington", "link": "https://www.youtube.com/@jherr", "niche": "Advanced Frontend React", "hook": "your advanced React, TypeScript, and full-stack frontend content for experienced developers", "product": "an AI React code assistant that helps developers architect components and debug complex frontend issues"},
    {"name": "Dwarkesh Patel", "link": "https://www.youtube.com/@DwarkeshPatel", "niche": "AI Alignment & Policy Podcasts", "hook": "your deep podcast conversations on AI alignment, policy, and the long-term future of intelligence", "product": "an AI platform with transparent safety practices and open dialogue about capabilities and limitations"},
    {"name": "MKBHD", "link": "https://www.youtube.com/@mkbhd", "niche": "Consumer Tech & Hardware", "hook": "your premium consumer tech reviews and the quality bar you set for honest hardware coverage", "product": "an AI assistant app with a polished consumer experience your audience would expect from a flagship tech product"},
    {"name": "Dave2D", "link": "https://www.youtube.com/@Dave2D", "niche": "Laptops & Gadget Design", "hook": "your clean, design-focused laptop and gadget reviews that help people buy smarter", "product": "an AI-powered device recommendation chatbot that matches users to the right laptop based on their workflow"},
    {"name": "Linus Tech Tips", "link": "https://www.youtube.com/@LinusTechTips", "niche": "Computing Hardware & Systems", "hook": "your computing hardware reviews, builds, and the LTT Labs approach to testing tech honestly", "product": "an AI PC building assistant chatbot that helps viewers pick compatible parts and optimize their setups"},
    {"name": "Austin Evans", "link": "https://www.youtube.com/@austinevans", "niche": "Hardware & Gaming Tech", "hook": "your hardware and gaming tech reviews that balance performance, value, and everyday usability", "product": "an AI tech advisor chatbot that helps gamers and creators find the right hardware for their setup"},
    {"name": "Mrwhosetheboss", "link": "https://www.youtube.com/@mrwhosetheboss", "niche": "Mobile Tech & Gadget Reviews", "hook": "your mobile tech reviews and smartphone comparisons that millions trust before buying", "product": "an AI mobile assistant app with smart chatbot features designed for the smartphone power users you reach"},
    {"name": "JerryRigEverything", "link": "https://www.youtube.com/@JerryRigEverything", "niche": "Tech Durability & Hardware", "hook": "your durability tests and teardowns that reveal what's really inside the devices people buy", "product": "an AI repair and device support chatbot that helps users troubleshoot hardware issues post-purchase"},
    {"name": "Unbox Therapy", "link": "https://www.youtube.com/@unboxtherapy", "niche": "Consumer Tech & Gadget Unboxing", "hook": "your gadget unboxings and first-look coverage of the latest consumer tech hitting the market", "product": "an AI shopping assistant chatbot that helps viewers discover and compare the latest gadgets"},
    {"name": "The Tech Chap", "link": "https://www.youtube.com/@TheTechChap", "niche": "Laptops & High-End Gadgets", "hook": "your laptop reviews and high-end gadget coverage tailored for professionals and creators", "product": "an AI laptop finder chatbot that recommends the best machine based on use case, budget, and workflow"},
    {"name": "Daniel Bourke", "link": "https://www.youtube.com/@mrdbourke", "niche": "Machine Learning Tutorials", "hook": "your end-to-end machine learning project tutorials that take viewers from zero to deployed model", "product": "an AI/ML learning platform with guided chatbot support for students building their first models"},
    {"name": "Web Dev Simplified", "link": "https://www.youtube.com/@WebDevSimplified", "niche": "Web Development Tutorials", "hook": "your simplified web development tutorials that cut through complexity and teach practical skills", "product": "an AI web dev tutor chatbot that gives learners instant help on HTML, CSS, and JavaScript concepts"},
    {"name": "DeepLearning.AI", "link": "https://www.youtube.com/@Deeplearningai", "niche": "ML/DL Courses & News", "hook": "your Andrew Ng-affiliated deep learning courses and AI education that millions of learners rely on", "product": "an AI learning companion chatbot that supplements ML courses with on-demand Q&A and practice"},
    {"name": "Henry AI Labs", "link": "https://www.youtube.com/@henryailabs", "niche": "AI Research Updates", "hook": "your timely AI research update videos that keep practitioners current on the latest breakthroughs", "product": "an AI research digest platform that auto-summarizes new papers and lets users chat with findings"},
    {"name": "ArXiv Insights", "link": "https://www.youtube.com/@ArxivInsights", "niche": "ML Research Summaries", "hook": "your ArXiv paper breakdowns that make cutting-edge ML research accessible to a wider audience", "product": "an AI paper-reading assistant that generates summaries and answers questions about new research"},
    {"name": "Clever Programmer", "link": "https://www.youtube.com/@CleverProgrammer", "niche": "Coding & AI Tools", "hook": "your coding tutorials and AI tools content that helps developers level up and land jobs", "product": "an AI coding bootcamp companion with chatbot-powered interview prep and project feedback"},
    {"name": "Net Ninja", "link": "https://www.youtube.com/@NetNinja", "niche": "Web Development Tutorials", "hook": "your structured web development crash courses covering everything from HTML to Node and beyond", "product": "an AI web development tutor that follows along with your crash course format for instant learner support"},
    {"name": "Sebastian Lague", "link": "https://www.youtube.com/@SebastianLague", "niche": "Coding & Algorithms", "hook": "your coding adventures and algorithm visualizations that make computer science concepts come alive", "product": "an AI algorithm visualizer with a chatbot that explains CS concepts step by step"},
    {"name": "Academind", "link": "https://www.youtube.com/@academind", "niche": "Web/JS Frameworks & Tutorials", "hook": "your comprehensive web and JavaScript framework tutorials from React to Node and beyond", "product": "an AI framework tutor chatbot that helps developers learn React, Vue, and Angular through conversation"},
    {"name": "CodeWithChris", "link": "https://www.youtube.com/@CodeWithChris", "niche": "iOS App Development", "hook": "your iOS app development tutorials that guide beginners through building real Swift applications", "product": "an AI Swift coding assistant that helps aspiring iOS developers debug and learn while building apps"},
    {"name": "CS Dojo", "link": "https://www.youtube.com/@CSDojo", "niche": "Python & Coding Bootcamp", "hook": "your Python programming and computer science fundamentals that launched so many coding careers", "product": "an AI Python tutor chatbot designed for beginners following a structured CS curriculum"},
    {"name": "Abdul Bari", "link": "https://www.youtube.com/@abdul_bari", "niche": "Algorithms & Data Structures", "hook": "your algorithms and data structures lectures that CS students worldwide use to ace their courses", "product": "an AI DSA tutor that walks students through algorithm problems with the clarity your lectures provide"},
    {"name": "Tech With Tim", "link": "https://www.youtube.com/@TechWithTim", "niche": "Python, ML & Game Dev", "hook": "your Python, machine learning, and game development project tutorials for hands-on learners", "product": "an AI project mentor chatbot that guides developers through Python and ML builds step by step"},
    {"name": "Hussein Nasser", "link": "https://www.youtube.com/@hnasr", "niche": "Computer Networks & Dev", "hook": "your backend engineering and computer networking deep dives for developers who want to understand systems", "product": "an AI backend architecture assistant that answers system design and networking questions via chatbot"},
    {"name": "Ben Awad", "link": "https://www.youtube.com/@bawad", "niche": "Full-Stack Dev", "hook": "your full-stack development vlogs and projects that show the real day-to-day of building software", "product": "an AI pair-programming assistant that helps indie developers ship full-stack features faster"},
    {"name": "Brackeys", "link": "https://www.youtube.com/@Brackeys", "niche": "Game Development & Unity", "hook": "your Unity game development tutorials that introduced an entire generation to game dev", "product": "an AI game dev assistant that helps Unity developers debug scripts and design game mechanics via chatbot"},
    {"name": "Gary Explains", "link": "https://www.youtube.com/@GaryExplains", "niche": "Tech Explainers", "hook": "your deep technical explainers on mobile processors, AI chips, and how modern technology actually works", "product": "an AI chip and hardware explainer chatbot that answers technical questions about processors and AI acceleration"},
    {"name": "Engineer Man", "link": "https://www.youtube.com/@EngineerMan", "niche": "Software Engineering", "hook": "your software engineering tips, code reviews, and practical advice for working developers", "product": "an AI code review chatbot that gives developers instant feedback on best practices and clean code"},
    {"name": "Krish Naik", "link": "https://www.youtube.com/@krishnaik06", "niche": "Data Science & ML", "hook": "your data science and end-to-end machine learning tutorials used by aspiring ML engineers everywhere", "product": "an AI data science mentor chatbot that guides learners through ML projects from EDA to deployment"},
    {"name": "ColdFusion", "link": "https://www.youtube.com/@ColdFusion", "niche": "Tech Documentary & AI", "hook": "your tech documentary storytelling that covers AI history, industry shifts, and the companies shaping tech", "product": "an AI platform with a compelling story behind it that fits the narrative-driven tech coverage you create"},
    {"name": "CodeBullet", "link": "https://www.youtube.com/@CodeBullet", "niche": "AI Programming Experiments", "hook": "your entertaining AI programming experiments where you let algorithms loose on game development challenges", "product": "an AI game-building platform that lets creators experiment with AI-driven game logic and agents"},
    {"name": "Derek Banas", "link": "https://www.youtube.com/@derekbanas", "niche": "Programming Tutorials", "hook": "your massive library of programming tutorials spanning dozens of languages and frameworks", "product": "an AI multi-language coding tutor chatbot that supports learners across the many languages you teach"},
    {"name": "TheNewBoston", "link": "https://www.youtube.com/@thenewboston", "niche": "General Programming", "hook": "your foundational programming tutorials that helped millions of developers write their first lines of code", "product": "an AI programming tutor chatbot built for beginners discovering coding for the first time"},
    {"name": "Codebasics", "link": "https://www.youtube.com/@codebasics", "niche": "Data Science & Python", "hook": "your data science and Python tutorials with real business case studies that make analytics practical", "product": "an AI data analytics chatbot that helps analysts query data and generate insights conversationally"},
    {"name": "Data School", "link": "https://www.youtube.com/@dataschool", "niche": "Pandas & ML Tutorials", "hook": "your Pandas and scikit-learn tutorials that data scientists rely on for clean, practical instruction", "product": "an AI data analysis assistant that helps users write Pandas queries and build ML models through chat"},
    {"name": "Keith Galli", "link": "https://www.youtube.com/@KeithGalli", "niche": "Data Science & Python", "hook": "your data science portfolio projects and Python tutorials that help people break into the field", "product": "an AI portfolio coach chatbot that guides aspiring data scientists through projects and job prep"},
    {"name": "The Cherno", "link": "https://www.youtube.com/@TheCherno", "niche": "C++ Game Engine Dev", "hook": "your C++ game engine development series where you build Hazel from scratch", "product": "an AI C++ coding assistant optimized for game engine development and systems-level programming"},
    {"name": "ProgrammingKnowledge", "link": "https://www.youtube.com/@ProgrammingKnowledge", "niche": "Programming Tutorials", "hook": "your wide-ranging programming tutorials covering tools, languages, and frameworks for all skill levels", "product": "an AI coding help chatbot that supports learners across the diverse topics your channel covers"},
    {"name": "Programming with Mosh", "link": "https://www.youtube.com/@programmingwithmosh", "niche": "Full-Stack & Career Dev", "hook": "your polished full-stack and career development courses that take developers from beginner to job-ready", "product": "an AI career and coding mentor chatbot that supplements your courses with 24/7 learner support"},
    {"name": "Neso Academy", "link": "https://www.youtube.com/@nesoacademy", "niche": "CS & Engineering Tutorials", "hook": "your computer science and engineering lectures that students use to supplement their university courses", "product": "an AI CS tutor chatbot that explains algorithms, digital logic, and engineering concepts on demand"},
    {"name": "Python Engineer", "link": "https://www.youtube.com/@patloeber", "niche": "Python ML/DS Tutorials", "hook": "your concise Python, machine learning, and data science tutorials for efficient learning", "product": "an AI Python ML assistant that helps developers write, debug, and optimize data science code via chat"},
    {"name": "Coding Addict", "link": "https://www.youtube.com/@CodingAddict", "niche": "Web Dev Projects", "hook": "your project-based web development tutorials that teach by building real applications", "product": "an AI project-building chatbot that guides developers through full-stack web app projects step by step"},
    {"name": "Applied AI Course", "link": "https://www.youtube.com/@AppliedAICourse", "niche": "ML/AI Theory & Courses", "hook": "your applied AI and machine learning theory courses that bridge math and real-world implementation", "product": "an AI/ML course companion chatbot that helps students work through theory and coding exercises"},
    {"name": "Dad the Engineer", "link": "https://www.youtube.com/@DadtheEngineer", "niche": "Electronics & STEM", "hook": "your electronics and STEM projects that make engineering approachable for families and hobbyists", "product": "an AI electronics troubleshooting chatbot that helps makers debug circuits and choose components"},
    {"name": "Chris Hawkes", "link": "https://www.youtube.com/@noobtoprofessional", "niche": "Dev Career & Advice", "hook": "your developer career advice and coding journey content for people breaking into tech", "product": "an AI career mentor chatbot that helps aspiring developers plan their learning path and prepare for jobs"},
    {"name": "Coding Garden", "link": "https://www.youtube.com/@CodingGarden", "niche": "Live Coding & Web Dev", "hook": "your live coding streams and collaborative web development sessions with the dev community", "product": "an AI live-coding companion that helps stream viewers follow along and get unstuck during builds"},
    {"name": "Kaggle", "link": "https://www.youtube.com/@kaggle", "niche": "Data Science & Competitions", "hook": "your data science competition walkthroughs and ML tutorials from the world's largest data science community", "product": "an AI Kaggle competition assistant that helps data scientists explore datasets and iterate on models faster"},
    {"name": "Akshay Saini", "link": "https://www.youtube.com/@akshaymarch7", "niche": "Advanced JavaScript Core Concepts", "hook": "your Namaste JavaScript series and deep dives into JavaScript internals that advanced devs swear by", "product": "an AI JavaScript tutor that explains closures, prototypes, and async concepts the way your series does"},
    {"name": "ArjanCodes", "link": "https://www.youtube.com/@ArjanCodes", "niche": "Software Design & Python", "hook": "your software design patterns and clean Python architecture content for professional developers", "product": "an AI software design reviewer that suggests architecture improvements and design pattern recommendations via chat"},
    {"name": "ByCloud AI", "link": "https://www.youtube.com/@bycloudAI", "niche": "Cloud AI & ML Deployments", "hook": "your cloud AI and ML deployment tutorials for getting models into production on AWS and beyond", "product": "a cloud-native AI deployment platform with one-click chatbot and agent hosting for production workloads"},
    {"name": "ByteByteGo", "link": "https://www.youtube.com/@ByteByteGo", "niche": "System Design & Tech Architecture", "hook": "your system design interview prep and tech architecture explainers used by engineers at top companies", "product": "an AI system design coach chatbot that walks engineers through architecture decisions and trade-offs"},
    {"name": "Clement Mihailescu", "link": "https://www.youtube.com/@ClementMihailescu", "niche": "Software Engineering Careers & DSA", "hook": "your AlgoExpert platform and coding interview content that helps developers land jobs at FAANG companies", "product": "an AI interview prep chatbot with adaptive coding challenges and system design practice"},
    {"name": "CodeWithHarry", "link": "https://www.youtube.com/@CodeWithHarry", "niche": "Full-Stack Web Dev & Programming", "hook": "your Hindi-English full-stack web development tutorials that make programming accessible to millions", "product": "an AI coding tutor chatbot with multilingual support for learners following your courses"},
    {"name": "Computerphile", "link": "https://www.youtube.com/@Computerphile", "niche": "Computer Science Theory & Algorithms", "hook": "your computer science theory videos with university professors explaining algorithms, security, and AI fundamentals", "product": "an AI CS professor chatbot that explains theoretical concepts with the academic rigor your audience expects"},
    {"name": "Corbin Brown", "link": "https://www.youtube.com/@Corbin_Brown", "niche": "Python & Machine Learning Engineering", "hook": "your Python machine learning engineering tutorials focused on building production ML systems", "product": "an AI MLOps assistant that helps ML engineers deploy, monitor, and iterate on models via chatbot"},
    {"name": "Dani", "link": "https://www.youtube.com/@Danidev", "niche": "Game Development & Physics Engines", "hook": "your game development devlogs and physics engine builds that inspire indie developers worldwide", "product": "an AI game development assistant that helps indie devs with physics, shaders, and game logic through chat"},
    {"name": "David Bombal", "link": "https://www.youtube.com/@davidbombal", "niche": "IT Networking & Ethical Hacking", "hook": "your IT networking labs and ethical hacking tutorials for cybersecurity and network professionals", "product": "an AI network troubleshooting chatbot that helps IT pros diagnose and resolve infrastructure issues"},
    {"name": "ExplainingComputers", "link": "https://www.youtube.com/@ExplainingComputers", "niche": "Computing Hardware & Linux OS", "hook": "your single-board computer reviews, Linux tutorials, and hands-on computing hardware projects", "product": "an AI Linux and hardware assistant chatbot that helps makers configure systems and troubleshoot setups"},
    {"name": "Gamefromscratch", "link": "https://www.youtube.com/@gamefromscratch", "niche": "Game Development Tools & Engines", "hook": "your game engine comparisons and game development tool reviews that help devs pick the right stack", "product": "an AI game engine advisor chatbot that recommends tools and helps developers get started with new engines"},
    {"name": "Gamers Nexus", "link": "https://www.youtube.com/@GamersNexus", "niche": "PC Hardware Benchmarking", "hook": "your rigorous PC hardware benchmarking and investigative journalism on thermal design and performance", "product": "an AI PC optimization chatbot that helps viewers tune their builds based on workload and budget"},
    {"name": "Gaurav Sen", "link": "https://www.youtube.com/@gkcs", "niche": "System Design & AI", "hook": "your system design and AI architecture videos that prepare engineers for senior-level technical interviews", "product": "an AI system design mentor chatbot with adaptive mock interviews and architecture feedback"},
    {"name": "GDQuest", "link": "https://www.youtube.com/@Gdquest", "niche": "Godot Engine Game Development", "hook": "your Godot engine tutorials and open-source game development education for the indie community", "product": "an AI Godot game dev assistant that helps developers write GDScript and design game systems via chat"},
    {"name": "Greg Isenberg", "link": "https://www.youtube.com/@GregIsenberg", "niche": "AI Agents & SaaS Startups", "hook": "your startup ideas, AI agent builds, and community-driven SaaS content for indie founders", "product": "an AI agent builder platform for launching chatbot-powered SaaS products your founder audience would love to try"},
    {"name": "Harkirat Singh", "link": "https://www.youtube.com/@harkirat1", "niche": "Full-Stack Dev & Blockchain", "hook": "your full-stack development cohorts and blockchain project builds for the next generation of Indian developers", "product": "an AI full-stack mentor chatbot that supports students through your cohort-style learning projects"},
    {"name": "Hitesh Choudhary", "link": "https://www.youtube.com/@HiteshCodeLab", "niche": "Web Frameworks & Software Dev", "hook": "your web framework tutorials and software development courses covering the full modern stack", "product": "an AI web development tutor chatbot that helps learners across the frameworks and tools you teach"},
    {"name": "IppSec", "link": "https://www.youtube.com/@IppSec", "niche": "Penetration Testing", "hook": "your Hack The Box walkthroughs and penetration testing tutorials revered by the cybersecurity community", "product": "an AI cybersecurity training chatbot that helps aspiring pentesters practice and learn exploit techniques safely"},
    {"name": "Jeff Geerling", "link": "https://www.youtube.com/@JeffGeerling", "niche": "Single-Board Computers & Hardware", "hook": "your Raspberry Pi clusters, homelab builds, and single-board computer projects that push hardware limits", "product": "an AI homelab assistant chatbot that helps makers configure Pi clusters, Docker setups, and self-hosted services"},
    {"name": "Joma Tech", "link": "https://www.youtube.com/@JomaTech", "niche": "Silicon Valley Careers & Tech", "hook": "your Silicon Valley career satire and tech industry insights that resonate with every software engineer", "product": "an AI career coaching chatbot with a fun, relatable tone that helps devs navigate tech careers"},
    {"name": "Jonas Tyroller", "link": "https://www.youtube.com/@JonasTyroller", "niche": "Indie Game Dev", "hook": "your indie game development journey and Unity tutorials for solo developers building their dream games", "product": "an AI indie game dev mentor chatbot that helps solo creators with game design, code, and marketing decisions"},
    {"name": "Jon Gjengset", "link": "https://www.youtube.com/@JonGjengset", "niche": "Advanced Rust Systems Programming", "hook": "your advanced Rust live coding sessions and systems programming content for experienced developers", "product": "an AI Rust programming assistant that helps developers with ownership, lifetimes, and systems-level debugging"},
    {"name": "Kalle Hallden", "link": "https://www.youtube.com/@Hallden_", "niche": "Python Automation & Dev Vlogs", "hook": "your Python automation projects and developer lifestyle content that makes coding look creative and fun", "product": "an AI Python automation builder that helps viewers create scripts and automate workflows through chat"},
    {"name": "LGR", "link": "https://www.youtube.com/@LGR", "niche": "Retro Technology & Computing", "hook": "your retro technology reviews and nostalgic computing content that celebrates tech history", "product": "an AI retro tech encyclopedia chatbot that answers questions about vintage hardware and computing history"},
    {"name": "Liam Ottley", "link": "https://www.youtube.com/@LiamOttley", "niche": "AI Automation Agencies & Agents", "hook": "your AI automation agency blueprint and AI agent business content for entrepreneurs building AI services", "product": "a white-label AI agent platform that agency owners can rebrand and sell to clients"},
    {"name": "Loi Liang Yang", "link": "https://www.youtube.com/@LoiLiangYang", "niche": "Cloud Security & AWS", "hook": "your AWS cloud security tutorials and hands-on labs for cloud engineers and security professionals", "product": "an AI cloud security assistant that audits AWS configurations and answers security questions via chatbot"},
    {"name": "Mental Outlaw", "link": "https://www.youtube.com/@MentalOutlaw", "niche": "Cybersecurity, Linux & Privacy", "hook": "your cybersecurity, Linux, and digital privacy content for people who want to stay secure online", "product": "an AI privacy and security advisor chatbot that helps users harden their systems and understand threats"},
    {"name": "Milan Jovanović", "link": "https://www.youtube.com/@MilanJovanovicTech", "niche": "C# Software Architecture", "hook": "your C# software architecture patterns and .NET best practices for building maintainable enterprise apps", "product": "an AI .NET architecture reviewer chatbot that suggests clean code improvements and design patterns"},
    {"name": "Modern Vintage Gamer", "link": "https://www.youtube.com/@ModernVintageGamer", "niche": "Console Architecture & Retrogaming", "hook": "your console architecture deep dives and retro gaming technical analysis that fascinates hardware enthusiasts", "product": "an AI retro gaming encyclopedia chatbot that explains console hardware, emulation, and gaming history"},
    {"name": "NeetCode", "link": "https://www.youtube.com/@NeetCode", "niche": "Coding Interviews & DSA", "hook": "your NeetCode roadmap and coding interview solutions that have become essential prep for tech interviews", "product": "an AI coding interview coach chatbot with adaptive problem hints and pattern recognition training"},
    {"name": "Nick Chapsas", "link": "https://www.youtube.com/@nickchapsas", "niche": ".NET & C# Software Engineering", "hook": "your .NET and C# best practices content that senior engineers rely on for writing better code", "product": "an AI .NET code assistant that reviews C# code and suggests modern .NET patterns via chatbot"},
    {"name": "Optimum Tech", "link": "https://www.youtube.com/@optimumtech", "niche": "Custom PC Hardware & ITX Builds", "hook": "your compact ITX PC builds and hardware optimization guides for enthusiasts who want maximum performance per liter", "product": "an AI PC building chatbot specialized in SFF and ITX builds with compatibility checking"},
    {"name": "PwnFunction", "link": "https://www.youtube.com/@PwnFunction", "niche": "Web Application Security", "hook": "your animated web security explainers on XSS, CSRF, and vulnerabilities that make infosec accessible", "product": "an AI web security scanner chatbot that helps developers understand and fix common vulnerabilities"},
    {"name": "Retro Game Corps", "link": "https://www.youtube.com/@RetroGameCorps", "niche": "Retro Hardware Emulation", "hook": "your retro handheld reviews and emulation setup guides that help gamers build the ultimate portable library", "product": "an AI retro emulation setup assistant that recommends devices, configs, and ROM management workflows"},
    {"name": "Robert Miles AI Safety", "link": "https://www.youtube.com/@RobertMilesAISafety", "niche": "AI Safety & ML Alignment", "hook": "your AI safety and alignment explainers that make complex x-risk topics understandable for everyone", "product": "an AI platform with published safety practices and alignment considerations your audience would want to scrutinize"},
    {"name": "Sam Witteveen AI", "link": "https://www.youtube.com/@samwitteveenai", "niche": "LangChain, LLMs & Agentic AI", "hook": "your LangChain tutorials and agentic AI builds that show developers how to ship LLM-powered applications", "product": "an LLM agent builder platform with LangChain-compatible integrations for production chatbot deployments"},
    {"name": "Seytonic", "link": "https://www.youtube.com/@Seytonic", "niche": "Hardware Hacking & Raspberry Pi", "hook": "your hardware hacking projects and Raspberry Pi builds for makers who love tinkering with electronics", "product": "an AI maker assistant chatbot that helps with Raspberry Pi configs, GPIO wiring, and project troubleshooting"},
    {"name": "Sonny Sangha", "link": "https://www.youtube.com/@SonnySangha", "niche": "Full-Stack Next.js & AI Agents", "hook": "your full-stack Next.js clone projects and AI agent builds that teach modern web development by doing", "product": "a Next.js AI agent starter kit with chatbot components your audience can integrate into their clone projects"},
    {"name": "take U forward", "link": "https://www.youtube.com/@takeUforward", "niche": "Algorithms & Data Structures", "hook": "your Striver's SDE sheet and DSA content that Indian CS students use as their primary interview prep resource", "product": "an AI DSA coach chatbot with adaptive problem-solving hints aligned to your sheet's structured approach"},
    {"name": "TechLead", "link": "https://www.youtube.com/@TechLead", "niche": "Silicon Valley Tech Careers", "hook": "your ex-Google/Facebook engineer perspective on Silicon Valley careers, tech culture, and coding", "product": "an AI tech career advisor chatbot with insights for engineers navigating big tech and startup paths"},
    {"name": "The 8-Bit Guy", "link": "https://www.youtube.com/@The8BitGuy", "niche": "Retrocomputing & Restoration", "hook": "your retro computer restoration projects and vintage computing history that preserve tech heritage", "product": "an AI vintage computing assistant chatbot that helps collectors identify, repair, and restore retro hardware"},
    {"name": "The AI Grid", "link": "https://www.youtube.com/@TheAiGrid", "niche": "AI Software & Industry Analysis", "hook": "your AI software reviews and industry analysis that helps viewers navigate the crowded AI tools landscape", "product": "an AI software platform launching soon that your audience would benefit from an honest, detailed review of"},
    {"name": "The Cyber Mentor", "link": "https://www.youtube.com/@TCMSecurityAcademy", "niche": "Ethical Hacking & Blue Team", "hook": "your ethical hacking courses and blue team training that launch cybersecurity careers", "product": "an AI cybersecurity lab assistant chatbot for hands-on ethical hacking practice and certification prep"},
    {"name": "The PC Security Channel", "link": "https://www.youtube.com/@thepcsecuritychannel", "niche": "Antivirus & Malware Analysis", "hook": "your antivirus tests and malware analysis videos that reveal which security products actually protect users", "product": "an AI threat detection chatbot that helps users understand malware behavior and choose real protection"},
    {"name": "Traversy Media", "link": "https://www.youtube.com/@TraversyMedia", "niche": "Full-Stack Web Dev & DevOps", "hook": "your full-stack web development crash courses and project builds that millions of developers learned from", "product": "an AI web dev project mentor chatbot that guides learners through the same project-based approach you teach"},
    {"name": "zSecurity", "link": "https://www.youtube.com/@zSecurity", "niche": "Ethical Hacking & Wireless Security", "hook": "your ethical hacking and wireless security courses that train the next generation of penetration testers", "product": "an AI pentesting practice chatbot with guided labs for wireless and network security training"},
    {"name": "ML Street Talk", "link": "https://www.youtube.com/@MachineLearningStreetTalk", "niche": "Deep AI Discussions", "hook": "your ML Street Talk podcast deep dives with researchers debating the biggest questions in AI", "product": "an AI research discussion platform where practitioners can explore and debate model capabilities via chat"},
    {"name": "Real Python", "link": "https://www.youtube.com/@realpython", "niche": "Python Tutorials & Tips", "hook": "your Real Python tutorials and tips that help developers write better, more Pythonic code every day", "product": "an AI Python code reviewer chatbot that suggests Pythonic improvements and explains best practices"},
]


def build_email(creator: dict) -> dict:
    name = creator["name"]
    subject = f"Collaboration Opportunity for {name}"
    body = f"""Hi {name},

I came across your channel and {creator["hook"]}.

I work with AI and tech brands looking to partner with creators in the tech and programming space.

We're currently looking for creators to promote {creator["product"]}.

Would this be relevant to you?

Best,
Dhurim Halili"""
    return {
        "name": name,
        "channelLink": creator["link"],
        "niche": creator["niche"],
        "subject": subject,
        "body": body,
    }


def main():
    out_dir = Path(__file__).parent
    emails = [build_email(c) for c in CREATORS]

    # CSV for mail merge
    csv_path = out_dir / "creator-outreach-emails.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["name", "channelLink", "niche", "subject", "body"],
        )
        writer.writeheader()
        writer.writerows(emails)

    # Markdown for copy-paste
    md_path = out_dir / "creator-outreach-emails.md"
    lines = [
        "# Creator Outreach Emails",
        "",
        f"**From:** Dhurim Halili  ",
        f"**Total creators:** {len(emails)} (deduplicated from 130 — removed duplicate entries for The Cherno, Chris Hawkes, and Coding Garden)",
        "",
        "---",
        "",
    ]
    for i, e in enumerate(emails, 1):
        lines.extend([
            f"## {i}. {e['name']}",
            "",
            f"**Channel:** {e['channelLink']}  ",
            f"**Niche:** {e['niche']}  ",
            f"**Subject:** {e['subject']}",
            "",
            "```",
            e["body"],
            "```",
            "",
            "---",
            "",
        ])
    md_path.write_text("\n".join(lines), encoding="utf-8")

    # JSON for programmatic use
    json_path = out_dir / "creator-outreach-emails.json"
    json_path.write_text(json.dumps(emails, indent=2), encoding="utf-8")

    print(f"Generated {len(emails)} emails")
    print(f"  CSV: {csv_path}")
    print(f"  MD:  {md_path}")
    print(f"  JSON: {json_path}")


if __name__ == "__main__":
    main()
