import Papa from "papaparse";
import { Archive, ArrowDownAZ, ArrowLeft, ArrowRight, Columns3, Contact, Download, ExternalLink, FileSpreadsheet, Filter, Flag, LayoutGrid, List, Merge, MoreHorizontal, Plus, Upload, Users, X } from "lucide-react";
import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { Avatar, Button, EmptyState, FieldMergeReview, Input, Modal, PageHeader, SearchInput, Select, StatusBadge, Tabs, Textarea } from "../components/ui";
import { useData } from "../contexts/DataContext";
import { useToast } from "../contexts/ToastContext";
import { CSV_BOM, dateLabel, download, isPastDay, isTodayDay, isValidEmail, isValidUrl, lossReasonLabel, money, normalize, PRIORITY_LABELS, relativeTime, toCSV, today } from "../lib/utils";
import { ENTITY_STATUSES, STATUS_LABELS, type Brand, type BrandContact, type EntityStatus, type Priority } from "../types";

type BrandDraft = { name: string; domain: string; brand_type: string; contact_email: string; pipeline_status: EntityStatus; date_contacted: string; notes: string; next_action: string; priority: Priority; next_action_date: string };
const blankBrand: BrandDraft = { name: "", domain: "", brand_type: "", contact_email: "", pipeline_status: "new", date_contacted: "", notes: "", next_action: "", priority: "none", next_action_date: "" };
const brandValue = (draft: BrandDraft) => ({ ...draft, name: draft.name.trim(), domain: draft.domain.trim(), contact_email: draft.contact_email.trim(), priority: (["none", "soon", "urgent"] as const).includes(draft.priority) ? draft.priority : "none" as Priority, next_action_date: draft.next_action_date || null, date_contacted: draft.date_contacted || null });

export default function BrandsPage() {
  const data = useData(); const { toast } = useToast(); const [params, setParams] = useSearchParams();
  const [query, setQuery] = useState(""); const [view, setView] = useState(localStorage.getItem("if.brand-view") || "table");
  const [status, setStatus] = useState("all"); const [type, setType] = useState("all"); const [sort, setSort] = useState("newest"); const [filters, setFilters] = useState(false); const [priorityFilter, setPriorityFilter] = useState("all");
  const [selected, setSelected] = useState<string[]>([]); const [open, setOpen] = useState(false); const [draft, setDraft] = useState<BrandDraft>(blankBrand); const [duplicates, setDuplicates] = useState<string[]>([]); const [importOpen, setImportOpen] = useState(false);
  useEffect(() => { if (params.get("new")) setOpen(true); }, [params]);
  const close = () => { setOpen(false); setDraft(blankBrand); setDuplicates([]); setParams((current) => { current.delete("new"); return current; }, { replace: true }); };
  const types = Array.from(new Set(data.brands.filter((item) => !item.archived_at).map((item) => item.brand_type).filter(Boolean))).sort();
  const prioRank = (p: string) => (p === "urgent" ? 0 : p === "soon" ? 1 : 2);
  const cyclePriority = (brand: Brand) => {
    const next = brand.priority === "none" ? "soon" : brand.priority === "soon" ? "urgent" : ("none" as Priority);
    data.updateBrand(brand.id, { priority: next });
    toast(next === "none" ? `Priority cleared for ${brand.name}` : next === "urgent" ? `${brand.name} marked urgent — pinned to top` : `${brand.name} — follow up soon`);
  };
  const rows = useMemo(() => data.brands.filter((item) => !item.archived_at).filter((item) => (!query || [item.name, item.domain, item.contact_email, item.brand_type].some((value) => value.toLowerCase().includes(query.toLowerCase()))) && (status === "all" || item.pipeline_status === status) && (type === "all" || item.brand_type === type) && (priorityFilter === "all" || item.priority === priorityFilter)).sort((a, b) => { const pr = prioRank(a.priority) - prioRank(b.priority); if (pr !== 0) return pr; return sort === "name" ? a.name.localeCompare(b.name) : sort === "status" ? ENTITY_STATUSES.indexOf(a.pipeline_status) - ENTITY_STATUSES.indexOf(b.pipeline_status) : sort === "contacted" ? (b.date_contacted || "").localeCompare(a.date_contacted || "") : sort === "oldest" ? a.created_at.localeCompare(b.created_at) : b.created_at.localeCompare(a.created_at); }), [data.brands, query, status, type, priorityFilter, sort]);
  const create = (event: FormEvent) => { event.preventDefault(); const found = data.findBrandDuplicates(draft.name, draft.domain); if (found.length) { setDuplicates(found.map((item) => item.id)); return; } data.addBrand(brandValue(draft)); toast(`${draft.name} added to brands`); close(); };
  const mergeDraft = (id: string) => { data.updateBrand(id, Object.fromEntries(Object.entries(brandValue(draft)).filter(([, value]) => value !== "" && value !== null)) as Partial<Brand>); data.log(`Duplicate brand submission reviewed and merged`, "brand", id); toast("Brand merged. Contacts and campaigns remain connected."); close(); };
  const bulkStatus = (value: EntityStatus) => { selected.forEach((id) => data.updateBrand(id, { pipeline_status: value })); toast(`${selected.length} brands updated`); setSelected([]); };
  const exportRows = (records: Brand[]) => { download("influenceflow-brands.csv", toCSV(records.map((item) => ({ name: item.name, domain: item.domain, brand_type: item.brand_type, contact_email: item.contact_email, priority: item.priority, pipeline_status: item.pipeline_status, date_contacted: item.date_contacted || "", next_action: item.next_action || "", action_due: item.next_action_date || "", notes: item.notes || "" })), { name: "Company", domain: "Domain", brand_type: "Type", contact_email: "Email", priority: "Priority", pipeline_status: "Status", date_contacted: "Date contacted", next_action: "Next action", action_due: "Action due", notes: "Notes" }), "text/csv"); toast(`${records.length} brands exported`); };
  const changeView = (value: string) => { setView(value); localStorage.setItem("if.brand-view", value); };

  return <div className="entity-page"><PageHeader eyebrow="Partnership CRM" title="Brands" description="Keep companies, decision-makers and every active opportunity connected." actions={<><Button variant="secondary" onClick={() => setImportOpen(true)}><Upload size={15} /> Import</Button><Button variant="secondary" onClick={() => exportRows(rows)}><Download size={15} /> Export</Button><Button onClick={() => setOpen(true)}><Plus size={16} /> Add brand</Button></>} />
    <div className="entity-toolbar"><SearchInput value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search company, domain, email, type..." /><div className="toolbar-filters"><button className={filters ? "active" : ""} onClick={() => setFilters(!filters)}><Filter size={15} /> Filters</button><label className="inline-select"><ArrowDownAZ size={15} /><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Company A-Z</option><option value="status">Pipeline status</option><option value="contacted">Date contacted</option></select></label><div className="view-toggle"><button className={view === "table" ? "active" : ""} onClick={() => changeView("table")}><List size={15} /></button><button className={view === "kanban" ? "active" : ""} onClick={() => changeView("kanban")}><Columns3 size={15} /></button><button className={view === "cards" ? "active" : ""} onClick={() => changeView("cards")}><LayoutGrid size={15} /></button></div></div></div>
    {filters && <div className="filter-drawer compact-filters"><Select label="Pipeline status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option>{ENTITY_STATUSES.map((item) => <option key={item} value={item}>{STATUS_LABELS[item]}</option>)}</Select><Select label="Brand type" value={type} onChange={(event) => setType(event.target.value)}><option value="all">All types</option>{types.map((item) => <option key={item}>{item}</option>)}</Select><Select label="Priority" value={priorityFilter} onChange={(event) => setPriorityFilter(event.target.value)}><option value="all">Any priority</option><option value="urgent">Urgent</option><option value="soon">Follow up soon</option><option value="none">No priority</option></Select><Button variant="ghost" onClick={() => { setStatus("all"); setType("all"); setPriorityFilter("all"); }}>Clear filters</Button></div>}
    <div className="results-meta"><span><strong>{rows.length}</strong> brands</span></div>
    {selected.length > 0 && <div className="bulk-bar"><span><b>{selected.length}</b> selected</span><label>Status <select defaultValue="" onChange={(event) => bulkStatus(event.target.value as EntityStatus)}><option value="" disabled>Change to...</option>{ENTITY_STATUSES.map((item) => <option key={item} value={item}>{STATUS_LABELS[item]}</option>)}</select></label><button onClick={() => exportRows(rows.filter((item) => selected.includes(item.id)))}><Download size={15} /> Export</button><button onClick={() => { data.archive("brand", selected); toast("Brands archived"); setSelected([]); }}><Archive size={15} /> Archive</button><button onClick={() => setSelected([])}><X size={15} /></button></div>}
    {!rows.length ? <EmptyState icon={query ? "search" : "inbox"} title="No brands in this view" text="Add a company and keep every contact, campaign, and note in one place." action={<Button onClick={() => setOpen(true)}>Add brand</Button>} /> : view === "kanban" ? <BrandKanban brands={rows} /> : view === "cards" ? <BrandCards brands={rows} cyclePriority={cyclePriority} /> : <BrandTable brands={rows} selected={selected} setSelected={setSelected} cyclePriority={cyclePriority} />}
    <Modal open={open} onClose={close} title="Add brand" description="Create the company record first, then add people and campaigns." wide><form className="entity-form" onSubmit={create}><div className="form-grid"><Input label="Company name" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} required autoFocus /><Input label="Domain" value={draft.domain} onChange={(event) => setDraft({ ...draft, domain: event.target.value })} error={!isValidUrl(draft.domain) ? "Enter a valid domain" : ""} placeholder="brand.com" /><Input label="Brand type" value={draft.brand_type} onChange={(event) => setDraft({ ...draft, brand_type: event.target.value })} placeholder="Technology, lifestyle..." /><Input label="Contact email" type="email" value={draft.contact_email} onChange={(event) => setDraft({ ...draft, contact_email: event.target.value })} error={!isValidEmail(draft.contact_email) ? "Enter a valid email" : ""} /><Select label="Pipeline status" value={draft.pipeline_status} onChange={(event) => setDraft({ ...draft, pipeline_status: event.target.value as EntityStatus })}>{ENTITY_STATUSES.map((item) => <option key={item} value={item}>{STATUS_LABELS[item]}</option>)}</Select><Input label="Date contacted" type="date" value={draft.date_contacted} onChange={(event) => setDraft({ ...draft, date_contacted: event.target.value })} /><Input label="Next action" value={draft.next_action} onChange={(event) => setDraft({ ...draft, next_action: event.target.value })} placeholder="Return revised proposal" /><Select label="Priority" value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value as Priority })}><option value="none">No priority</option><option value="soon">Follow up soon</option><option value="urgent">Urgent</option></Select><Input label="Action due" type="date" value={draft.next_action_date} onChange={(event) => setDraft({ ...draft, next_action_date: event.target.value })} /></div><Textarea label="Notes" rows={3} value={draft.notes} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} />{duplicates.length > 0 && <div className="duplicate-warning"><div><Merge size={19} /><span><strong>Possible duplicate company</strong><p>Company names and domains are normalized before comparison.</p></span></div>{duplicates.map((id) => { const item = data.brands.find((brand) => brand.id === id); return item && <div className="duplicate-record" key={id}><Avatar name={item.name} /><span><strong>{item.name}</strong><small>{item.domain}</small></span><Button type="button" variant="secondary" size="sm" onClick={() => mergeDraft(id)}>Review & merge</Button></div>; })}</div>}<div className="modal-actions"><Button type="button" variant="ghost" onClick={close}>Cancel</Button><Button type="submit" disabled={!draft.name || !isValidEmail(draft.contact_email) || !isValidUrl(draft.domain)}>Check & add brand</Button></div></form></Modal>
    <ImportBrands open={importOpen} onClose={() => setImportOpen(false)} />
  </div>;
}

type BrandImportRow = BrandDraft & { row: number; errors: string[]; duplicate: boolean };

function ImportBrands({ open, onClose }: { open: boolean; onClose: () => void }) {
  const data = useData();
  const { toast } = useToast();
  const [mode, setMode] = useState("paste");
  const [text, setText] = useState("");
  const [rows, setRows] = useState<BrandImportRow[]>([]);
  const preview = (raw: string) => {
    const parsed = Papa.parse<string[]>(raw.trim(), { skipEmptyLines: true }).data;
    const hasHeader = parsed[0]?.some((cell) => /company|name|domain|email|type|brand|status/i.test(cell));
    const headers = (hasHeader ? parsed[0] : []).map((cell) => cell.trim().toLowerCase().replace(/[ .-]+/g, "_"));
    const column = (cells: string[], names: string[]) => {
      const index = headers.findIndex((header) => names.includes(header));
      return index >= 0 ? cells[index]?.trim() || "" : "";
    };
    const values = hasHeader ? parsed.slice(1) : parsed;
    const seen = new Set<string>();
    const seenDomains = new Set<string>();
    const next = values.map((cells, index) => {
      const trimmed = cells.map((cell) => cell?.trim() || "");
      const domainIndex = trimmed.findIndex((cell) => /^[\w.-]+\.[a-z]{2,}/i.test(cell) && !cell.includes("@") && !cell.includes(" "));
      const emailIndex = trimmed.findIndex((cell) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(cell));
      const name = hasHeader ? column(trimmed, ["company", "name", "brand"]) : trimmed[0] || "";
      const domain = (hasHeader ? column(trimmed, ["domain", "website", "url"]) : domainIndex >= 0 ? trimmed[domainIndex] : "").replace(/^https?:\/\//, "").replace(/\/+$/, "");
      const email = hasHeader ? column(trimmed, ["email", "contact_email"]) : emailIndex >= 0 ? trimmed[emailIndex] : "";
      const typeValue = hasHeader ? column(trimmed, ["type", "brand_type", "category"]) : "";
      const statusValue = hasHeader ? column(trimmed, ["status", "pipeline_status"]) : "new";
      const dateValue = hasHeader ? column(trimmed, ["date_contacted", "contacted", "date"]) : "";
      const priorityValue = hasHeader ? column(trimmed, ["priority"]).toLowerCase() : "";
      const dueValue = hasHeader ? column(trimmed, ["action_due", "due", "due_date"]) : "";
      const nextActionValue = hasHeader ? column(trimmed, ["next_action"]) : "";
      const key = normalize(name);
      const domKey = normalize(domain);
      const errors = [...(!name ? ["Name required"] : []), ...(!isValidEmail(email) ? ["Invalid email"] : []), ...(!isValidUrl(domain) ? ["Invalid domain"] : []), ...(statusValue && !ENTITY_STATUSES.includes(statusValue as EntityStatus) ? ["Invalid status"] : [])];
      const duplicate = seen.has(key) || Boolean(domKey && seenDomains.has(domKey)) || data.findBrandDuplicates(name, domain).length > 0;
      seen.add(key);
      if (domKey) seenDomains.add(domKey);
      return { ...blankBrand, row: index + 1 + (hasHeader ? 1 : 0), name, contact_email: email, domain, brand_type: typeValue, priority: (["none", "soon", "urgent"] as const).includes(priorityValue as Priority) ? (priorityValue as Priority) : "none", next_action_date: /^\d{4}-\d{2}-\d{2}$/.test(dueValue) ? dueValue : "", pipeline_status: (ENTITY_STATUSES.includes(statusValue as EntityStatus) ? statusValue : "new") as EntityStatus, date_contacted: /^\d{4}-\d{2}-\d{2}$/.test(dateValue) ? dateValue : "", next_action: nextActionValue, notes: hasHeader ? column(trimmed, ["notes"]) : "", errors, duplicate };
    });
    setRows(next);
  };
  const file = (event: ChangeEvent<HTMLInputElement>) => { const selected = event.target.files?.[0]; if (selected) selected.text().then(preview).catch(() => toast("Could not read that file", "error")); };
  const confirm = () => { const valid = rows.filter((row) => !row.errors.length && !row.duplicate); data.addBrands(valid.map(({ row: _row, errors: _errors, duplicate: _duplicate, ...item }) => brandValue(item))); toast(`${valid.length} brands imported. ${rows.length - valid.length} flagged rows skipped.`); setRows([]); setText(""); onClose(); };
  const template = () => download("influenceflow-brand-template.csv", CSV_BOM + "Company,Domain,Type,Email,Priority,Status,Date contacted,Action due,Next action,Notes\nNorthstar Labs,northstarlabs.com,Technology,partners@northstarlabs.com,urgent,new,2026-09-01,2026-09-05,Send intro deck,Annual program", "text/csv");
  return <Modal open={open} onClose={onClose} title="Import brands" description="Preview, validate, and deduplicate before companies reach your pipeline." wide><div className="import-flow"><Tabs active={mode} onChange={setMode} tabs={[{ value: "paste", label: "Paste rows" }, { value: "file", label: "Upload CSV" }]} />{!rows.length ? <>{mode === "paste" ? <div className="paste-zone"><Textarea value={text} onChange={(event) => setText(event.target.value)} rows={9} placeholder={`Northstar Labs, northstarlabs.com\nAster & Co., partners@aster.com, Lifestyle`} /><p>Accepted: Company + domain, or Company + email + type. Header rows are detected automatically.</p></div> : <label className="upload-zone"><FileSpreadsheet size={28} /><strong>Choose a CSV file</strong><span>CSV up to 5 MB. Nothing is imported before confirmation.</span><input type="file" accept=".csv,text/csv" onChange={file} /></label>}<button className="template-link" onClick={template}><Download size={14} /> Download CSV template</button><div className="modal-actions"><Button variant="ghost" onClick={onClose}>Cancel</Button>{mode === "paste" && <Button onClick={() => preview(text)} disabled={!text.trim()}>Preview rows</Button>}</div></> : <><div className="import-summary"><span><b>{rows.length}</b> parsed</span><span className="valid"><b>{rows.filter((row) => !row.errors.length && !row.duplicate).length}</b> ready</span><span className="invalid"><b>{rows.filter((row) => row.errors.length).length}</b> invalid</span><span className="duplicate"><b>{rows.filter((row) => row.duplicate).length}</b> duplicates</span></div><div className="import-table-wrap"><table className="import-table"><thead><tr><th>Row</th><th>Company</th><th>Domain / email</th><th>Type</th><th>Result</th></tr></thead><tbody>{rows.map((row) => <tr key={row.row} className={row.errors.length || row.duplicate ? "row-invalid" : ""}><td>{row.row}</td><td>{row.name || "Missing"}</td><td>{row.domain || row.contact_email || "Missing"}</td><td>{row.brand_type || "-"}</td><td>{row.errors.length ? row.errors.join(", ") : row.duplicate ? "Duplicate" : "Ready"}</td></tr>)}</tbody></table></div><div className="modal-actions"><Button variant="ghost" onClick={() => { setRows([]); setText(""); }}>Back</Button><Button onClick={confirm} disabled={!rows.some((row) => !row.errors.length && !row.duplicate)}>Import ready rows</Button></div></>}</div></Modal>;
}

function BrandTable({ brands, selected, setSelected, cyclePriority }: { brands: Brand[]; selected: string[]; setSelected: (value: string[]) => void; cyclePriority: (brand: Brand) => void }) { const data = useData(); const all = brands.every((item) => selected.includes(item.id)); return <><div className="data-table-wrap"><table className="data-table"><thead><tr><th><input type="checkbox" checked={all} onChange={() => setSelected(all ? [] : brands.map((item) => item.id))} /></th><th>Company</th><th>Type</th><th>Primary contact</th><th>Status</th><th>People</th><th>Next action</th><th /></tr></thead><tbody>{brands.map((item) => <tr key={item.id} className={item.priority !== "none" ? item.priority : ""}><td><input type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected(selected.includes(item.id) ? selected.filter((id) => id !== item.id) : [...selected, item.id])} /></td><td><div className="person-first"><button className={`flag-btn ${item.priority}`} title={item.priority === "none" ? "Set priority" : `${PRIORITY_LABELS[item.priority]} — click to change`} onClick={() => cyclePriority(item)}><Flag size={14} /></button><Link to={`/app/brands/${item.id}`} className="person-cell"><Avatar name={item.name} /><span><strong>{item.name}</strong><small>{item.domain || "No domain"}</small></span></Link></div></td><td>{item.brand_type || <span className="muted">Uncategorized</span>}</td><td><span className="stacked-cell"><strong>{item.contact_email || "No contact"}</strong><small>{dateLabel(item.date_contacted)}</small></span></td><td><StatusBadge status={item.pipeline_status} /></td><td><span className="people-count"><Users size={14} />{data.contacts.filter((contact) => contact.brand_id === item.id).length}</span></td><td><span className={item.next_action ? "next-action" : "muted"}>{item.next_action || "None set"}</span>{item.next_action_date && <small className={isPastDay(item.next_action_date) ? "due-overdue" : isTodayDay(item.next_action_date) ? "due-today" : "muted"}>{isPastDay(item.next_action_date) ? `Overdue · ${dateLabel(item.next_action_date)}` : isTodayDay(item.next_action_date) ? "Due today" : `Due ${dateLabel(item.next_action_date)}`}</small>}</td><td><Link to={`/app/brands/${item.id}`} className="row-action"><ArrowRight size={15} /></Link></td></tr>)}</tbody></table></div><div className="table-mobile-fallback"><BrandCards brands={brands} cyclePriority={cyclePriority} /></div></>; }

function BrandKanban({ brands }: { brands: Brand[] }) { const data = useData(); return <div className="kanban-board">{ENTITY_STATUSES.filter((status) => brands.some((item) => item.pipeline_status === status) || ["new", "contacted", "replied", "negotiating", "signed"].includes(status)).map((stage) => <section className="kanban-column" key={stage}><header><StatusBadge status={stage} /><span>{brands.filter((item) => item.pipeline_status === stage).length}</span></header><div>{brands.filter((item) => item.pipeline_status === stage).map((item) => <article className={`kanban-item ${item.priority !== "none" ? item.priority : ""}`} key={item.id}><Link to={`/app/brands/${item.id}`}><div><Avatar name={item.name} size="sm" /><strong>{item.name}</strong></div><p>{item.brand_type || "Uncategorized"}</p><span><b>{item.domain || "No domain"}</b><em>{data.contacts.filter((contact) => contact.brand_id === item.id).length} people</em></span></Link><select value={item.pipeline_status} onChange={(event) => data.updateBrand(item.id, { pipeline_status: event.target.value as EntityStatus })}>{ENTITY_STATUSES.map((item) => <option key={item} value={item}>{STATUS_LABELS[item]}</option>)}</select></article>)}</div></section>)}</div>; }

function BrandCards({ brands, cyclePriority }: { brands: Brand[]; cyclePriority: (brand: Brand) => void }) { const data = useData();   return <div className="mobile-card-grid">{brands.map((item) => <Link to={`/app/brands/${item.id}`} className={`entity-mobile-card ${item.priority !== "none" ? item.priority : ""}`} key={item.id}><header><Avatar name={item.name} /><div><strong>{item.name}</strong><span>{item.domain || "No domain"}</span></div><button className={`flag-btn ${item.priority}`} title={item.priority === "none" ? "Set priority" : `${PRIORITY_LABELS[item.priority]} — click to change`} onClick={(event) => { event.preventDefault(); cyclePriority(item); }}><Flag size={14} /></button><MoreHorizontal /></header><div><span><small>Type</small><b>{item.brand_type || "-"}</b></span><span><small>People</small><b>{data.contacts.filter((contact) => contact.brand_id === item.id).length}</b></span></div><footer><StatusBadge status={item.pipeline_status} /><span>{item.next_action || "No next action"}</span></footer></Link>)}</div>; }

type ContactDraft = { first_name: string; last_name: string; title: string; email: string; linkedin_url: string; pipeline_status: EntityStatus; date_contacted: string; notes: string };
const blankContact: ContactDraft = { first_name: "", last_name: "", title: "", email: "", linkedin_url: "", pipeline_status: "new", date_contacted: "", notes: "" };

export function BrandDetailPage() {
  const { id } = useParams(); const data = useData(); const { toast } = useToast(); const navigate = useNavigate(); const brand = data.brands.find((item) => item.id === id);
  const [contactOpen, setContactOpen] = useState(false); const [contactDraft, setContactDraft] = useState<ContactDraft>(blankContact); const [editing, setEditing] = useState<string | null>(null); const [notes, setNotes] = useState(brand?.notes || ""); const [mergeOpen, setMergeOpen] = useState(false); const [mergeId, setMergeId] = useState("");
  if (!brand) return <EmptyState title="Brand not found" text="This record may have been archived or removed." action={<Button onClick={() => navigate("/app/brands")}>Back to brands</Button>} />;
  const contacts = data.contacts.filter((item) => item.brand_id === brand.id); const campaigns = data.campaigns.filter((item) => item.brand_id === brand.id && !item.archived_at); const meetings = data.meetings.filter((item) => item.related_type === "brand" && item.related_id === brand.id); const activities = data.activities.filter((item) => item.entity_id === brand.id);
  const saveContact = (event: FormEvent) => { event.preventDefault(); const value = { ...contactDraft, brand_id: brand.id, date_contacted: contactDraft.date_contacted || null }; if (editing) data.updateContact(editing, value); else data.addContact(value); toast(editing ? "Contact updated" : "Contact added"); setContactOpen(false); setEditing(null); setContactDraft(blankContact); };
  const editContact = (contact: BrandContact) => { setEditing(contact.id); setContactDraft({ first_name: contact.first_name, last_name: contact.last_name, title: contact.title, email: contact.email, linkedin_url: contact.linkedin_url, pipeline_status: contact.pipeline_status, date_contacted: contact.date_contacted || "", notes: contact.notes }); setContactOpen(true); };
  return <div className="detail-page"><Link to="/app/brands" className="back-link"><ArrowLeft size={15} /> Brands</Link><header className="detail-header"><div className="detail-identity"><Avatar name={brand.name} size="lg" /><div><span className="eyebrow">Brand account</span><h1>{brand.name}</h1><div><StatusBadge status={brand.pipeline_status} /><span>{brand.brand_type || "Uncategorized"}</span><span>{brand.domain || "No domain"}</span>{brand.pipeline_status === "denied" && brand.lost_at ? <button className="lost-inline" onClick={() => data.reviewLoss("brand", brand.id)} title="Edit loss reason"><span>Lost · {lossReasonLabel(brand.lost_reason)} · {dateLabel(brand.lost_at)}</span></button> : brand.pipeline_status === "denied" ? <span className="muted">Closed early — no active deal</span> : null}</div></div></div><div className="page-actions"><Button variant="secondary" onClick={() => setMergeOpen(true)}><Merge size={15} /> Merge</Button><Button variant="secondary" onClick={() => data.updateBrand(brand.id, { pipeline_status: brand.pipeline_status === "signed" ? "negotiating" : "signed" })}>{brand.pipeline_status === "signed" ? "Reopen" : "Mark signed"}</Button><button className="icon-btn danger" onClick={() => { if (confirm(`Archive ${brand.name}?`)) { data.archive("brand", [brand.id]); navigate("/app/brands"); } }}><Archive size={17} /></button></div></header>
    <section className="detail-stats"><div><span>Campaign value</span><strong>{money(campaigns.reduce((sum, item) => sum + item.agreed_payment, 0))}</strong><small>{campaigns.length} campaigns</small></div><div><span>People</span><strong>{contacts.length}</strong><small>brand contacts</small></div><div><span>Active deals</span><strong>{campaigns.filter((item) => item.status === "active").length}</strong><small>in delivery</small></div><div><span>Relationship</span><strong className="date-stat">{dateLabel(brand.date_contacted)}</strong><small>first contacted</small></div></section>
    <div className="detail-grid"><main><section className="detail-section"><div className="detail-section-head"><div><span>Company</span><h2>Account details</h2></div><Button size="sm" variant="secondary" onClick={() => { const next = prompt("Next action", brand.next_action || ""); if (next !== null) data.updateBrand(brand.id, { next_action: next }); }}>Set next action</Button></div><div className="contact-block"><div><small>Domain</small><strong>{brand.domain || "Not added"}</strong>{brand.domain && <a href={`https://${brand.domain.replace(/^https?:\/\//, "")}`} target="_blank" rel="noreferrer">Visit website <ExternalLink size={13} /></a>}</div><div><small>General contact</small><strong>{brand.contact_email || "Not added"}</strong>{brand.contact_email && <a href={`mailto:${brand.contact_email}`}>Send email <ExternalLink size={13} /></a>}</div><div><small>Next action</small><strong>{brand.next_action || "None set"}</strong>{brand.next_action_date && <small className={isPastDay(brand.next_action_date) ? "due-overdue" : isTodayDay(brand.next_action_date) ? "due-today" : "muted"}>{isPastDay(brand.next_action_date) ? `Overdue · ${dateLabel(brand.next_action_date)}` : isTodayDay(brand.next_action_date) ? "Due today" : `Due ${dateLabel(brand.next_action_date)}`}</small>}</div></div></section>
      <section className="detail-section"><div className="detail-section-head"><div><span>People</span><h2>Brand contacts</h2></div><Button size="sm" onClick={() => { setContactDraft(blankContact); setEditing(null); setContactOpen(true); }}><Plus size={14} /> Add person</Button></div>{contacts.length ? <div className="people-table"><table><thead><tr><th>Name</th><th>Role</th><th>Contact</th><th>Status</th><th>Contacted</th><th /></tr></thead><tbody>{contacts.map((contact) => <tr key={contact.id}><td><span className="person-cell"><Avatar name={`${contact.first_name} ${contact.last_name}`} size="sm" /><strong>{contact.first_name} {contact.last_name}</strong></span></td><td>{contact.title || "-"}</td><td><span className="contact-links"><a href={`mailto:${contact.email}`}>{contact.email || "No email"}</a>{contact.linkedin_url && <a href={contact.linkedin_url} target="_blank" rel="noreferrer"><Contact size={13} /> LinkedIn</a>}</span></td><td><StatusBadge status={contact.pipeline_status} /></td><td>{dateLabel(contact.date_contacted)}</td><td><button className="row-action" onClick={() => editContact(contact)}>Edit</button> <button className="row-action" title="Delete contact" onClick={() => { if (confirm(`Remove ${contact.first_name} ${contact.last_name} from ${brand.name}?`)) { data.deleteContact(contact.id); toast("Contact removed"); } }}><X size={14} /></button></td></tr>)}</tbody></table></div> : <EmptyState title="No people yet" text="Add the decision makers and day-to-day contacts behind this relationship." action={<Button onClick={() => setContactOpen(true)}>Add first contact</Button>} />}</section>
      <section className="detail-section"><div className="detail-section-head"><div><span>Campaigns</span><h2>Linked opportunities</h2></div><Link to={`/app/campaigns?new=1&brand=${brand.id}`}>New campaign <Plus size={14} /></Link></div><div className="linked-list">{campaigns.map((campaign) => <Link to={`/app/campaigns?id=${campaign.id}`} key={campaign.id}><span className="linked-icon"><LayoutGrid /></span><div><strong>{campaign.name}</strong><small>{campaign.creator_ids.length} influencers / Due {dateLabel(campaign.due_date)}</small></div><StatusBadge status={campaign.status} /><b>{money(campaign.agreed_payment)}</b><ArrowRight /></Link>)}{!campaigns.length && <p className="muted-copy">No campaigns linked to this brand.</p>}</div></section>
      <section className="detail-section"><div className="detail-section-head"><div><span>Notes</span><h2>Account context</h2></div><Button size="sm" variant="secondary" onClick={() => { data.updateBrand(brand.id, { notes }); toast("Notes saved"); }}>Save notes</Button></div><Textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={6} /><Input label="Action due" type="date" value={brand.next_action_date || ""} onChange={(event) => data.updateBrand(brand.id, { next_action_date: event.target.value || null })} /></section></main>
      <aside><section className="detail-side-section"><span>Pipeline</span><h2>Account status</h2><div className="status-rail">{ENTITY_STATUSES.slice(0, 6).map((stage) => <button key={stage} className={stage === brand.pipeline_status ? "current" : ENTITY_STATUSES.indexOf(stage) < ENTITY_STATUSES.indexOf(brand.pipeline_status) ? "passed" : ""} onClick={() => { data.updateBrand(brand.id, { pipeline_status: stage, date_contacted: stage === "contacted" && !brand.date_contacted ? today() : brand.date_contacted }); toast(`Moved to ${STATUS_LABELS[stage]}`); }}><i /><span><strong>{STATUS_LABELS[stage]}</strong>{stage === brand.pipeline_status && <small>Current stage</small>}</span></button>)}</div><div className="priority-seg"><span>Priority</span><Tabs active={brand.priority} onChange={(value) => { data.updateBrand(brand.id, { priority: value as Priority }); toast(value === "none" ? "Priority cleared" : `Priority: ${PRIORITY_LABELS[value]}`); }} tabs={[{ value: "none", label: "None" }, { value: "soon", label: "Soon" }, { value: "urgent", label: "Urgent" }]} /></div></section><section className="detail-side-section"><span>Meetings</span><h2>Relationship time</h2>{meetings.map((meeting) => <Link className="mini-meeting" to="/app/calendar" key={meeting.id}><b>{new Date(meeting.starts_at).getDate()}</b><span>{meeting.title}<small>{dateLabel(meeting.starts_at)}</small></span></Link>)}{!meetings.length && <p className="muted-copy">No meetings linked yet.</p>}</section><section className="detail-side-section"><span>Activity</span><h2>Audit trail</h2><div className="mini-activity">{activities.map((activity) => <p key={activity.id}>{activity.text}<small>{relativeTime(activity.at)}</small></p>)}</div></section></aside></div>
    <Modal open={contactOpen} onClose={() => setContactOpen(false)} title={editing ? "Edit brand contact" : "Add brand contact"}><form className="entity-form" onSubmit={saveContact}><div className="form-grid"><Input label="First name" value={contactDraft.first_name} onChange={(e) => setContactDraft({ ...contactDraft, first_name: e.target.value })} required /><Input label="Last name" value={contactDraft.last_name} onChange={(e) => setContactDraft({ ...contactDraft, last_name: e.target.value })} required /><Input label="Title" value={contactDraft.title} onChange={(e) => setContactDraft({ ...contactDraft, title: e.target.value })} /><Input label="Email" type="email" value={contactDraft.email} onChange={(e) => setContactDraft({ ...contactDraft, email: e.target.value })} /><Input label="LinkedIn URL" value={contactDraft.linkedin_url} onChange={(e) => setContactDraft({ ...contactDraft, linkedin_url: e.target.value })} /><Select label="Status" value={contactDraft.pipeline_status} onChange={(e) => setContactDraft({ ...contactDraft, pipeline_status: e.target.value as EntityStatus })}>{ENTITY_STATUSES.map((item) => <option key={item} value={item}>{STATUS_LABELS[item]}</option>)}</Select><Input label="Date contacted" type="date" value={contactDraft.date_contacted} onChange={(e) => setContactDraft({ ...contactDraft, date_contacted: e.target.value })} /></div><Textarea label="Notes" value={contactDraft.notes} onChange={(e) => setContactDraft({ ...contactDraft, notes: e.target.value })} /><div className="modal-actions"><Button type="button" variant="ghost" onClick={() => setContactOpen(false)}>Cancel</Button><Button>{editing ? "Save contact" : "Add contact"}</Button></div></form></Modal>
    <Modal open={mergeOpen} onClose={() => setMergeOpen(false)} title="Merge duplicate brand" description="Choose a company to keep, then select the winning value for every field." wide><div className="merge-picker"><div className="merge-current"><Avatar name={brand.name} /><span><strong>Duplicate: {brand.name}</strong><small>{brand.domain}</small></span></div><Select label="Keep this brand" value={mergeId} onChange={(event) => setMergeId(event.target.value)}><option value="">Choose a company</option>{data.brands.filter((item) => item.id !== brand.id && !item.archived_at).map((item) => <option key={item.id} value={item.id}>{item.name} / {item.domain}</option>)}</Select>{mergeId && <FieldMergeReview keep={data.brands.find((item) => item.id === mergeId) as unknown as Record<string, unknown>} remove={brand as unknown as Record<string, unknown>} fields={[{ key: "name", label: "Company" }, { key: "domain", label: "Domain" }, { key: "brand_type", label: "Type" }, { key: "contact_email", label: "Email" }, { key: "pipeline_status", label: "Status" }, { key: "date_contacted", label: "Contacted" }, { key: "notes", label: "Notes" }]} onConfirm={(merged) => { data.mergeBrands(mergeId, brand.id, merged as Partial<Brand>); toast("Brands merged with contacts, campaigns and meetings preserved"); navigate(`/app/brands/${mergeId}`); }} />}</div></Modal>
  </div>;
}