import { AlertTriangle, Archive, ArrowLeft, ArrowRight, BarChart3, CalendarClock, Check, CheckCircle2, CircleDollarSign, Download, Plus, SlidersHorizontal, Sparkles, Users, X } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { Avatar, Button, EmptyState, Input, Modal, PageHeader, SearchInput, Select, StatusBadge, Textarea } from "../components/ui";
import { useData } from "../contexts/DataContext";
import { useToast } from "../contexts/ToastContext";
import { compact, dateLabel, download, isOverdue, money, relativeTime, toCSV, uid } from "../lib/utils";
import { CAMPAIGN_STATUSES, PLATFORMS, STATUS_LABELS, type Campaign, type CampaignStatus, type Platform } from "../types";

type CampaignDraft = { name: string; brand_id: string; platform: Platform; deliverables: string; agreed_payment: string; agency_percent: string; status: CampaignStatus; start_date: string; due_date: string; notes: string; next_action: string; creator_ids: string[] };
const blank: CampaignDraft = { name: "", brand_id: "", platform: "YouTube", deliverables: "", agreed_payment: "", agency_percent: "20", status: "negotiating", start_date: "", due_date: "", notes: "", next_action: "", creator_ids: [] };

export default function CampaignsPage() {
  const data = useData(); const { toast } = useToast(); const [params, setParams] = useSearchParams();
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [brand, setBrand] = useState("all"); const [sort, setSort] = useState("due"); const [open, setOpen] = useState(false); const [draft, setDraft] = useState<CampaignDraft>(blank);
  const activeCampaign = data.campaigns.find((item) => item.id === params.get("id"));
  useEffect(() => { if (params.get("new")) { setDraft({ ...blank, brand_id: params.get("brand") || "", creator_ids: params.get("creator") ? [params.get("creator")!] : [] }); setOpen(true); } }, [params]);
  const close = () => { setOpen(false); setParams((current) => { current.delete("new"); current.delete("brand"); current.delete("creator"); return current; }, { replace: true }); };
  const rows = useMemo(() => data.campaigns.filter((item) => !item.archived_at).filter((item) => (!query || item.name.toLowerCase().includes(query.toLowerCase())) && (status === "all" || item.status === status) && (brand === "all" || item.brand_id === brand)).sort((a, b) => sort === "value" ? b.agreed_payment - a.agreed_payment : sort === "newest" ? b.created_at.localeCompare(a.created_at) : sort === "status" ? CAMPAIGN_STATUSES.indexOf(a.status) - CAMPAIGN_STATUSES.indexOf(b.status) : a.due_date.localeCompare(b.due_date)), [data.campaigns, query, status, brand, sort]);
  const create = (event: FormEvent) => { event.preventDefault(); const campaign = data.addCampaign({ name: draft.name, brand_id: draft.brand_id, platform: draft.platform, deliverables: draft.deliverables.split("\n").map((text) => text.trim()).filter(Boolean).map((text) => ({ id: uid(), text, done: false })), agreed_payment: Number(draft.agreed_payment), agency_percent: Number(draft.agency_percent), status: draft.status, start_date: draft.start_date, due_date: draft.due_date, notes: draft.notes, next_action: draft.next_action, creator_ids: draft.creator_ids }); toast(`${campaign.name} created`); close(); setParams({ id: campaign.id }); };
  const livePayout = Number(draft.agreed_payment || 0) * Number(draft.agency_percent || 0) / 100;
  const conflictRows = data.campaigns.filter((campaign) => campaign.status === "active" && campaign.brand_id === draft.brand_id && campaign.creator_ids.some((id) => draft.creator_ids.includes(id)));
  const totals = { value: rows.reduce((sum, item) => sum + item.agreed_payment, 0), payout: rows.reduce((sum, item) => sum + item.creator_payout, 0), active: rows.filter((item) => item.status === "active").length, overdue: rows.filter((item) => item.status === "active" && isOverdue(item.due_date)).length };
  const exportCampaigns = () => { download("influenceflow-campaigns.csv", toCSV(rows.map((item) => ({ name: item.name, brand: data.brands.find((brand) => brand.id === item.brand_id)?.name, platform: item.platform, agreed_payment: item.agreed_payment, agency_percent: item.agency_percent, creator_payout: item.creator_payout, status: item.status, start_date: item.start_date, due_date: item.due_date, influencers: item.creator_ids.map((id) => data.creators.find((creator) => creator.id === id)?.name).filter(Boolean).join("; "), notes: item.notes }))), "text/csv"); toast("Campaigns exported"); };
  if (activeCampaign) return <CampaignDetail campaign={activeCampaign} close={() => setParams((current) => { current.delete("id"); return current; })} />;

  return <div className="campaigns-page"><PageHeader eyebrow="Revenue workspace" title="Campaigns" description="Run every deal from negotiation through delivery, payout and close." actions={<><Button variant="secondary" onClick={exportCampaigns}><Download size={15} /> Export</Button><Button onClick={() => setOpen(true)}><Plus size={16} /> New campaign</Button></>} />
    <section className="campaign-metrics"><div><span>Pipeline value <CircleDollarSign /></span><strong>{money(totals.value)}</strong><small>Across {rows.length} campaigns</small></div><div><span>Creator payouts <Users /></span><strong>{money(totals.payout)}</strong><small>{totals.value ? Math.round(totals.payout / totals.value * 100) : 0}% of deal value</small></div><div><span>Active work <Sparkles /></span><strong>{totals.active}</strong><small>{rows.filter((item) => item.status === "completed").length} completed</small></div><div className={totals.overdue ? "metric-alert" : ""}><span>Overdue <CalendarClock /></span><strong>{totals.overdue}</strong><small>{totals.overdue ? "Needs attention" : "Everything on track"}</small></div></section>
    <div className="entity-toolbar"><SearchInput value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search campaigns..." /><div className="toolbar-filters"><label className="inline-select"><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option>{CAMPAIGN_STATUSES.map((item) => <option key={item} value={item}>{STATUS_LABELS[item]}</option>)}</select></label><label className="inline-select"><select value={brand} onChange={(event) => setBrand(event.target.value)}><option value="all">All brands</option>{data.brands.filter((item) => !item.archived_at).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="inline-select"><SlidersHorizontal size={14} /><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="due">Due date</option><option value="value">Deal value</option><option value="newest">Newest</option><option value="status">Status</option></select></label></div></div>
    <div className="results-meta"><span><strong>{rows.length}</strong> campaigns</span></div>
    {!rows.length ? <EmptyState title="Create your first campaign" text="Connect a brand and the right influencers, calculate payouts, and keep delivery on track." action={<Button onClick={() => setOpen(true)}>New campaign</Button>} /> : <div className="campaign-list">{rows.map((campaign) => { const brandItem = data.brands.find((item) => item.id === campaign.brand_id); const creators = data.creators.filter((item) => campaign.creator_ids.includes(item.id)); const progress = campaign.deliverables.length ? Math.round(campaign.deliverables.filter((item) => item.done).length / campaign.deliverables.length * 100) : 0; const overdue = campaign.status === "active" && isOverdue(campaign.due_date); return <button key={campaign.id} className={overdue ? "overdue" : ""} onClick={() => setParams({ id: campaign.id })}><div className="campaign-status-line"><StatusBadge status={campaign.status} />{overdue && <span className="overdue-label"><AlertTriangle size={12} /> Overdue</span>}</div><div className="campaign-title"><span className="campaign-logo">{brandItem?.name[0] || "C"}</span><div><h3>{campaign.name}</h3><p>{brandItem?.name || "No brand"} / {campaign.platform}</p></div></div><div className="campaign-people"><div>{creators.slice(0, 4).map((creator) => <Avatar name={creator.name} size="sm" key={creator.id} />)}</div><span>{creators.length} influencer{creators.length === 1 ? "" : "s"}</span></div><div className="campaign-progress"><span><b>{progress}%</b> deliverables</span><i><b style={{ width: `${progress}%` }} /></i></div><div className="campaign-dates"><span><small>Due date</small><b>{dateLabel(campaign.due_date)}</b></span><span><small>Deal value</small><b>{money(campaign.agreed_payment)}</b></span></div><ArrowRight className="campaign-arrow" /></button>; })}</div>}
    <Modal open={open} onClose={close} title="Create campaign" description="Build the deal, calculate the split, then assign creators with full performance context." wide><form onSubmit={create} className="campaign-form"><section><h3>Campaign details</h3><div className="form-grid"><Input label="Campaign name" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} required autoFocus /><Select label="Brand" value={draft.brand_id} onChange={(event) => setDraft({ ...draft, brand_id: event.target.value })} required><option value="">Choose a brand</option>{data.brands.filter((item) => !item.archived_at).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select label="Platform" value={draft.platform} onChange={(event) => setDraft({ ...draft, platform: event.target.value as Platform })}>{PLATFORMS.map((item) => <option key={item}>{item}</option>)}</Select><Select label="Status" value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as CampaignStatus })}>{CAMPAIGN_STATUSES.map((item) => <option key={item} value={item}>{STATUS_LABELS[item]}</option>)}</Select><Input label="Start date" type="date" value={draft.start_date} onChange={(event) => setDraft({ ...draft, start_date: event.target.value })} required /><Input label="Due date" type="date" value={draft.due_date} onChange={(event) => setDraft({ ...draft, due_date: event.target.value })} required /></div><Textarea label="Deliverables" hint="One deliverable per line. Each becomes a trackable checklist item." rows={4} value={draft.deliverables} onChange={(event) => setDraft({ ...draft, deliverables: event.target.value })} placeholder={`1 x 60-second integration\n3 x story frames\n30-day usage rights`} /></section>
      <section className="payment-builder"><h3>Payment math</h3><div className="form-grid"><Input label="Agreed payment ($)" type="number" min="0" value={draft.agreed_payment} onChange={(event) => setDraft({ ...draft, agreed_payment: event.target.value })} required /><Input label="Creator payout percent" type="number" min="0" max="100" value={draft.agency_percent} onChange={(event) => setDraft({ ...draft, agency_percent: event.target.value })} required /></div><div className="live-math"><span><small>Deal value</small><strong>{money(Number(draft.agreed_payment))}</strong></span><i><X size={13} /> {draft.agency_percent || 0}%</i><span><small>Creator payout</small><strong>{money(livePayout)}</strong></span><span><small>Agency revenue</small><strong>{money(Number(draft.agreed_payment) - livePayout)}</strong></span></div></section>
      <section><div className="form-section-head"><div><h3>Assign influencers</h3><p>Engagement, platform, niche, views and status stay visible while you choose.</p></div><span>{draft.creator_ids.length} selected</span></div><CreatorPicker selected={draft.creator_ids} onChange={(creator_ids) => setDraft({ ...draft, creator_ids })} />{conflictRows.length > 0 && <div className="conflict-warning"><AlertTriangle /><div><strong>Potential brand conflict</strong><p>The selected influencer is already assigned to an active campaign for this brand: {conflictRows.map((item) => item.name).join(", ")}.</p></div></div>}</section>
      <section><div className="form-grid"><Input label="Next action" value={draft.next_action} onChange={(event) => setDraft({ ...draft, next_action: event.target.value })} placeholder="Send agreement for signature" /><Textarea label="Notes" value={draft.notes} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} rows={3} /></div></section><div className="modal-actions"><Button type="button" variant="ghost" onClick={close}>Cancel</Button><Button type="submit" disabled={!draft.name || !draft.brand_id || !draft.start_date || !draft.due_date}>Create campaign</Button></div></form></Modal>
  </div>;
}

function CreatorPicker({ selected, onChange }: { selected: string[]; onChange: (ids: string[]) => void }) {
  const data = useData(); const [query, setQuery] = useState(""); const [platform, setPlatform] = useState("all"); const [sort, setSort] = useState("engagement");
  const creators = data.creators.filter((item) => !item.archived_at && (!query || [item.name, item.niche].some((value) => value.toLowerCase().includes(query.toLowerCase()))) && (platform === "all" || item.platform === platform)).sort((a, b) => sort === "views" ? b.avg_views - a.avg_views : sort === "name" ? a.name.localeCompare(b.name) : b.engagement_rate - a.engagement_rate);
  return <div className="creator-picker"><div className="picker-tools"><SearchInput value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name or niche..." /><select value={platform} onChange={(event) => setPlatform(event.target.value)}><option value="all">All platforms</option>{PLATFORMS.map((item) => <option key={item}>{item}</option>)}</select><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="engagement">Highest engagement</option><option value="views">Highest avg. views</option><option value="name">Name A-Z</option></select></div><div className="picker-list">{creators.map((creator) => <button type="button" className={selected.includes(creator.id) ? "selected" : ""} key={creator.id} onClick={() => onChange(selected.includes(creator.id) ? selected.filter((id) => id !== creator.id) : [...selected, creator.id])}><span className="picker-check">{selected.includes(creator.id) && <Check size={13} />}</span><Avatar name={creator.name} size="sm" /><span><strong>{creator.name}</strong><small>{creator.platform} / {creator.niche || "No niche"}</small></span><em><strong>{creator.engagement_rate}%</strong><small>engagement</small></em><em><strong>{compact(creator.avg_views)}</strong><small>avg. views</small></em><StatusBadge status={creator.pipeline_status} /></button>)}</div></div>;
}

function CampaignDetail({ campaign, close }: { campaign: Campaign; close: () => void }) {
  const data = useData(); const { toast } = useToast(); const brand = data.brands.find((item) => item.id === campaign.brand_id); const creators = data.creators.filter((item) => campaign.creator_ids.includes(item.id)); const meetings = data.meetings.filter((item) => item.related_type === "campaign" && item.related_id === campaign.id); const activities = data.activities.filter((item) => item.entity_id === campaign.id); const [notes, setNotes] = useState(campaign.notes); const [assignOpen, setAssignOpen] = useState(false); const [selected, setSelected] = useState(campaign.creator_ids); const [completionOpen, setCompletionOpen] = useState(false);
  const progress = campaign.deliverables.length ? Math.round(campaign.deliverables.filter((item) => item.done).length / campaign.deliverables.length * 100) : 0; const overdue = campaign.status === "active" && isOverdue(campaign.due_date); const dueSoon = campaign.status === "active" && !overdue && new Date(campaign.due_date).getTime() - Date.now() < 5 * 86400000;
  const status = (next: CampaignStatus) => { data.updateCampaign(campaign.id, { status: next }); toast(`Campaign moved to ${STATUS_LABELS[next]}`); if (next === "completed" && creators.some((item) => !["roster", "signed"].includes(item.pipeline_status))) setCompletionOpen(true); };
  return <div className="detail-page campaign-detail"><button className="back-link" onClick={close}><ArrowLeft size={15} /> Campaigns</button><header className="detail-header"><div className="detail-identity"><span className="campaign-detail-mark"><BarChart3 /></span><div><span className="eyebrow">{brand?.name || "Campaign"}</span><h1>{campaign.name}</h1><div><StatusBadge status={campaign.status} /><span>{campaign.platform}</span>{overdue && <span className="due-state overdue-label"><AlertTriangle size={12} /> Overdue</span>}{dueSoon && <span className="due-state soon">Due soon</span>}</div></div></div><div className="page-actions"><Select value={campaign.status} onChange={(event) => status(event.target.value as CampaignStatus)}>{CAMPAIGN_STATUSES.map((item) => <option key={item} value={item}>{STATUS_LABELS[item]}</option>)}</Select><button className="icon-btn danger" onClick={() => { if (confirm("Archive this campaign?")) { data.archive("campaign", [campaign.id]); toast("Campaign archived"); close(); } }}><Archive size={17} /></button></div></header>
    <section className="detail-stats"><div><span>Deal value</span><strong>{money(campaign.agreed_payment)}</strong><small>agreed payment</small></div><div><span>Agency revenue</span><strong>{money(campaign.agreed_payment - campaign.creator_payout)}</strong><small>{100 - campaign.agency_percent}% retained</small></div><div><span>Creator payout</span><strong>{money(campaign.creator_payout)}</strong><small>{campaign.agency_percent}% of value</small></div><div><span>Delivery progress</span><strong>{progress}%</strong><small>{campaign.deliverables.filter((item) => item.done).length}/{campaign.deliverables.length} complete</small></div></section>
    <div className="detail-grid"><main><section className="detail-section"><div className="detail-section-head"><div><span>Delivery</span><h2>Deliverables</h2></div><span className="detail-progress"><i><b style={{ width: `${progress}%` }} /></i>{progress}%</span></div><div className="deliverable-list">{campaign.deliverables.map((item) => <label key={item.id} className={item.done ? "done" : ""}><input type="checkbox" checked={item.done} onChange={() => data.updateCampaign(campaign.id, { deliverables: campaign.deliverables.map((deliverable) => deliverable.id === item.id ? { ...deliverable, done: !deliverable.done } : deliverable) })} /><span><Check size={13} /></span><strong>{item.text}</strong></label>)}{!campaign.deliverables.length && <p className="muted-copy">No deliverables added.</p>}</div></section>
      <section className="detail-section"><div className="detail-section-head"><div><span>Talent</span><h2>Assigned influencers</h2></div><Button size="sm" variant="secondary" onClick={() => setAssignOpen(true)}>Manage assignment</Button></div><div className="assigned-grid">{creators.map((creator) => <Link to={`/app/influencers/${creator.id}`} key={creator.id}><Avatar name={creator.name} /><span><strong>{creator.name}</strong><small>{creator.platform} / {creator.niche}</small></span><em><b>{creator.engagement_rate}% ER</b><small>{compact(creator.avg_views)} avg views</small></em><StatusBadge status={creator.pipeline_status} /></Link>)}</div></section>
      <section className="detail-section"><div className="detail-section-head"><div><span>Notes</span><h2>Campaign context</h2></div><Button size="sm" variant="secondary" onClick={() => { data.updateCampaign(campaign.id, { notes }); toast("Campaign notes saved"); }}>Save notes</Button></div><Textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={6} /><Input label="Next action" value={campaign.next_action || ""} onChange={(event) => data.updateCampaign(campaign.id, { next_action: event.target.value })} /></section></main>
      <aside><section className="detail-side-section"><span>Schedule</span><h2>Key dates</h2><div className="campaign-date-rail"><div><i /><span><small>Starts</small><strong>{dateLabel(campaign.start_date)}</strong></span></div><div className={overdue ? "overdue" : ""}><i /><span><small>Due</small><strong>{dateLabel(campaign.due_date)}</strong></span></div></div></section><section className="detail-side-section"><span>Brand</span><h2>Account</h2>{brand ? <Link className="brand-link-block" to={`/app/brands/${brand.id}`}><Avatar name={brand.name} /><span><strong>{brand.name}</strong><small>{brand.domain}</small></span><ArrowRight /></Link> : <p className="muted-copy">No brand linked.</p>}</section><section className="detail-side-section"><span>Meetings</span><h2>Campaign calls</h2>{meetings.map((meeting) => <Link className="mini-meeting" to="/app/calendar" key={meeting.id}><b>{new Date(meeting.starts_at).getDate()}</b><span>{meeting.title}<small>{dateLabel(meeting.starts_at)}</small></span></Link>)}{!meetings.length && <Link className="text-link" to={`/app/calendar?new=1&type=campaign&id=${campaign.id}`}>Schedule a meeting <Plus size={13} /></Link>}</section><section className="detail-side-section"><span>Activity</span><h2>Audit trail</h2><div className="mini-activity">{activities.map((activity) => <p key={activity.id}>{activity.text}<small>{relativeTime(activity.at)}</small></p>)}</div></section></aside></div>
    <Modal open={assignOpen} onClose={() => setAssignOpen(false)} title="Manage influencers" description="Compare performance before changing this campaign roster." wide><CreatorPicker selected={selected} onChange={setSelected} /><div className="modal-actions"><Button variant="ghost" onClick={() => setAssignOpen(false)}>Cancel</Button><Button onClick={() => { data.updateCampaign(campaign.id, { creator_ids: selected }); toast("Campaign assignments updated"); setAssignOpen(false); }}>Save assignments</Button></div></Modal>
    <Modal open={completionOpen} onClose={() => setCompletionOpen(false)} title="Campaign completed" description="Keep your relationship pipeline in sync with the win."><div className="completion-prompt"><CheckCircle2 /><h3>Move assigned influencers forward?</h3><p>Mark these creators as Roster or Signed and add the change to their audit trail.</p><div>{creators.filter((item) => !["roster", "signed"].includes(item.pipeline_status)).map((creator) => <span key={creator.id}><Avatar name={creator.name} size="sm" />{creator.name}</span>)}</div><div className="modal-actions"><Button variant="ghost" onClick={() => setCompletionOpen(false)}>Not now</Button><Button variant="secondary" onClick={() => { creators.forEach((item) => data.updateCreator(item.id, { pipeline_status: "roster" })); toast("Influencers moved to Roster"); setCompletionOpen(false); }}>Move to Roster</Button><Button onClick={() => { creators.forEach((item) => data.updateCreator(item.id, { pipeline_status: "signed" })); toast("Influencers marked Signed"); setCompletionOpen(false); }}>Mark Signed</Button></div></div></Modal>
  </div>;
}