import { AlertTriangle, Bell, Check, ChevronRight, FileText, Gauge, Pencil, Plus, Database, Download, FileJson, HardDriveDownload, LockKeyhole, RefreshCcw, RotateCcw, Save, ShieldCheck, Sparkles, Trash2, Upload, UserRound, X } from "lucide-react";
import { useEffect, useRef, useState, type ChangeEvent } from "react";
import { useLocation } from "react-router-dom";
import { Avatar, Button, EmptyState, Input, Modal, PageHeader, Select, Tabs } from "../components/ui";
import { useAuth } from "../contexts/AuthContext";
import { useData } from "../contexts/DataContext";
import { useToast } from "../contexts/ToastContext";
import { creatorScore, dateLabel, DEFAULT_RATING_WEIGHTS, download, normalize, RATING_DIMS, ratingScore, resolveWeights, TEMPLATE_TOKENS, toCSV, uid, weightShares, type RatingWeightsValue } from "../lib/utils";
import { Stars, Textarea } from "../components/ui";
import type { EmailTemplate, ThemeName, WorkspaceData } from "../types";

const WEIGHT_HELP: Record<string, string> = {
  audience: "Decides whether the brand's buyers are even watching. The #1 factor in most agency scorecards.",
  niche: "Content and tone that match the product make the message land and keep the brand safe.",
  engagement: "Quality of attention — and the best signal for bought followers.",
  consistency: "Reliability: posts on schedule, delivers on time. Easiest gap to manage with a brief.",
};

function ScoringSettings() {
  const data = useData();
  const { toast } = useToast();
  const saved = resolveWeights(data.profile.rating_weights);
  const [weights, setWeights] = useState<RatingWeightsValue>(saved);
  useEffect(() => setWeights(resolveWeights(data.profile.rating_weights)), [data.profile.rating_weights]);
  const shares = weightShares(weights);
  const custom = !!data.profile.rating_weights;
  const dirty = (Object.keys(weights) as (keyof RatingWeightsValue)[]).some((k) => weights[k] !== saved[k]);
  const sample = { stars_demographics: 5, stars_niche: 4, stars_engagement: 2, stars_consistency: 3 };
  const rated = data.creators.filter((c) => !c.archived_at && RATING_DIMS.some((d) => (c[d.key] || 0) > 0));
  const changed = rated.filter((c) => Math.round(creatorScore(c, weights) * 10) !== Math.round(creatorScore(c, data.profile.rating_weights) * 10)).length;
  return <section id="scoring" className="settings-section"><div className="settings-heading"><span><Gauge /></span><div><h2>Creator scoring</h2><p>How the four evaluation stars combine into each influencer's overall rating.</p></div></div><div className="settings-body">
    <div className="weight-list">{RATING_DIMS.map((dim) => <div className="weight-row" key={dim.key}><div><strong>{dim.label}</strong><small>{WEIGHT_HELP[dim.weight]}</small></div><input type="range" min={0} max={60} step={5} value={weights[dim.weight]} onChange={(event) => setWeights({ ...weights, [dim.weight]: Number(event.target.value) })} aria-label={`${dim.label} weight`} /><b>{shares[dim.weight]}%</b></div>)}</div>
    <div className="weight-example"><span>Example: Audience 5★ · Brand fit 4★ · Engagement 2★ · Consistency 3★</span><span>Overall <Stars value={ratingScore(sample, weights)} showValue /> <small>(a plain average would say {((5 + 4 + 2 + 3) / 4).toFixed(1)})</small></span></div>
    <p className="settings-note">Set a factor to 0% if it doesn't matter for your agency — it then never moves the score. Unrated factors are always left out rather than counted as zero.{dirty && rated.length ? ` Saving re-scores ${changed} of your ${rated.length} rated influencers.` : ""}</p>
    <div className="settings-actions"><Button disabled={!dirty} onClick={() => { data.updateProfile({ rating_weights: weights }); toast("Scoring weights saved — every influencer re-scored"); }}><Save size={15} /> Save weights</Button><Button variant="ghost" disabled={!custom && !dirty} onClick={() => { setWeights(DEFAULT_RATING_WEIGHTS); data.updateProfile({ rating_weights: null }); toast("Back to market-standard weights (35 / 30 / 20 / 15)"); }}><RotateCcw size={15} /> Market defaults</Button></div>
  </div></section>;
}

const STARTER_TEMPLATES: Omit<EmailTemplate, "id">[] = [
  { name: "First outreach — creator", subject: "Paid partnership idea for {name}", body: "Hi {first_name},\n\nI've been following your {niche} content on {platform} and love how engaged your community is.\n\nI'm {my_name} and I run creator partnerships at our agency — we're putting together a campaign that feels like a natural fit for your channel. Budget is confirmed and the brief is flexible around your style.\n\nWould you be open to a quick call this week, or should I send the details over email?\n\nBest,\n{my_name}" },
  { name: "Follow-up (no reply)", subject: "Re: Paid partnership idea for {name}", body: "Hi {first_name},\n\nJust floating this back to the top of your inbox — happy to share budget and timing so you can decide quickly.\n\nIf now isn't the right time, no worries at all; just let me know and I won't chase.\n\nBest,\n{my_name}" },
  { name: "Brand pitch", subject: "Creators for {company}'s next campaign", body: "Hi {first_name},\n\nWe manage a roster of vetted creators in your space and have a few who fit {company}'s audience closely — strong engagement, brand-safe content, and proven conversions.\n\nCould I send over a short shortlist with rates and recent results?\n\nBest,\n{my_name}" },
];

function TemplateSettings() {
  const data = useData();
  const { toast } = useToast();
  const templates = data.profile.email_templates || [];
  const [editing, setEditing] = useState<EmailTemplate | null>(null);
  const saveAll = (next: EmailTemplate[], message: string) => { data.updateProfile({ email_templates: next }); toast(message); };
  return <section id="templates" className="settings-section"><div className="settings-heading"><span><FileText /></span><div><h2>Email templates</h2><p>Reusable outreach emails. Apply one from any influencer or brand profile — tokens fill in automatically.</p></div></div><div className="settings-body">
    {templates.length ? <div className="template-list">{templates.map((t) => <div className="template-row" key={t.id}><div><strong>{t.name}</strong><small>{t.subject || "No subject"}</small></div><button className="icon-btn" onClick={() => setEditing(t)} aria-label={`Edit ${t.name}`} title="Edit"><Pencil size={15} /></button><button className="icon-btn danger" onClick={() => { if (confirm(`Delete template "${t.name}"?`)) saveAll(templates.filter((x) => x.id !== t.id), "Template deleted"); }} aria-label={`Delete ${t.name}`} title="Delete"><Trash2 size={15} /></button></div>)}</div> : <EmptyState title="No templates yet" text="Start from proven starters, or write a draft on any profile and click Save as template." action={<Button variant="secondary" onClick={() => saveAll(STARTER_TEMPLATES.map((t) => ({ ...t, id: uid() })), "3 starter templates added")}><Sparkles size={15} /> Add starter templates</Button>} />}
    <div className="settings-actions"><Button variant="secondary" onClick={() => setEditing({ id: "", name: "", subject: "", body: "" })}><Plus size={15} /> New template</Button><span className="settings-note">Tokens: {TEMPLATE_TOKENS.join(" ")}</span></div>
    <Modal open={!!editing} onClose={() => setEditing(null)} title={editing?.id ? "Edit template" : "New template"} wide>{editing && <div className="entity-form"><Input label="Template name" value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value })} placeholder="First outreach — creator" autoFocus /><Input label="Subject" value={editing.subject} onChange={(event) => setEditing({ ...editing, subject: event.target.value })} /><Textarea label="Body" rows={10} value={editing.body} onChange={(event) => setEditing({ ...editing, body: event.target.value })} hint={`Tokens: ${TEMPLATE_TOKENS.join(" ")}`} /><div className="modal-actions"><Button variant="ghost" onClick={() => setEditing(null)}>Cancel</Button><Button disabled={!editing.name.trim()} onClick={() => { const value = { ...editing, name: editing.name.trim() }; saveAll(editing.id ? templates.map((t) => (t.id === editing.id ? value : t)) : [...templates, { ...value, id: uid() }], editing.id ? "Template updated" : "Template saved"); setEditing(null); }}>Save template</Button></div></div>}</Modal>
  </div></section>;
}

export function SettingsPage() {
  const data = useData(); const { user, updatePassword } = useAuth(); const { toast } = useToast(); const fileRef = useRef<HTMLInputElement>(null); const [name, setName] = useState(data.profile.display_name); const [pw1, setPw1] = useState(""); const [pw2, setPw2] = useState(""); const [preview, setPreview] = useState<WorkspaceData | null>(null); const [importError, setImportError] = useState(""); const [conflictMode, setConflictMode] = useState("skip");
  const location = useLocation();
  useEffect(() => { if (location.hash) requestAnimationFrame(() => document.getElementById(location.hash.slice(1))?.scrollIntoView({ behavior: "smooth" })); }, [location.hash]);
  const save = () => { data.updateProfile({ display_name: name.trim() }); toast("Workspace settings saved"); };
  const changePassword = async () => {
    if (pw1.length < 8) { toast("New password needs at least 8 characters", "error"); return; }
    if (pw1 !== pw2) { toast("Passwords do not match", "error"); return; }
    const message = await updatePassword(pw1);
    if (message) toast(message, "error");
    else { setPw1(""); setPw2(""); toast("Password updated"); }
  };
  const exportBackup = () => download(`influenceflow-backup-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify({ schema: "influenceflow-backup", version: 2, exported_at: new Date().toISOString(), data: { profile: data.profile, creators: data.creators, brands: data.brands, contacts: data.contacts, campaigns: data.campaigns, followups: data.followups, meetings: data.meetings, activities: data.activities, demoSeeded: false } }, null, 2));
  const readBackup = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setImportError(""); file.text().then((raw) => { try { const parsed = JSON.parse(raw) as { schema?: string; version?: number; data?: WorkspaceData } | WorkspaceData; const workspace = "data" in parsed && parsed.data ? parsed.data : parsed as WorkspaceData; if (!workspace || !Array.isArray(workspace.creators) || !Array.isArray(workspace.brands) || !Array.isArray(workspace.campaigns)) throw new Error("Missing creator, brand, or campaign collections."); setPreview({ ...workspace, contacts: workspace.contacts || [], followups: workspace.followups || [], meetings: workspace.meetings || [], activities: workspace.activities || [], profile: workspace.profile || data.profile, demoSeeded: false }); } catch (error) { setImportError(error instanceof Error ? error.message : "Invalid JSON backup"); } }).catch(() => setImportError("Could not read this file.")); };
  const importNow = () => { if (!preview) return; let next = preview; if (conflictMode !== "replace") { const creatorKeys = new Set(data.creators.map((item) => normalize(item.name))); const brandKeys = new Set(data.brands.map((item) => normalize(item.name))); next = { ...preview, profile: data.profile, creators: [...data.creators, ...preview.creators.filter((item) => conflictMode === "keep-both" || !creatorKeys.has(normalize(item.name)))], brands: [...data.brands, ...preview.brands.filter((item) => conflictMode === "keep-both" || !brandKeys.has(normalize(item.name)))], contacts: [...data.contacts, ...preview.contacts], campaigns: [...data.campaigns, ...preview.campaigns], followups: [...data.followups, ...(preview.followups || [])], meetings: [...data.meetings, ...preview.meetings], activities: [...preview.activities, ...data.activities] }; } data.importBackup(next); toast(`Backup imported: ${preview.creators.length} influencers, ${preview.brands.length} brands, ${preview.campaigns.length} campaigns`); setPreview(null); };
  const exportCollection = (type: "influencers" | "brands" | "contacts" | "campaigns") => {
    const built: { rows: Record<string, string | number | boolean | null | undefined>[]; headers: Record<string, string> } =
      type === "influencers"
        ? { rows: data.creators.map((item) => ({ name: item.name, email: item.contact_email, channel: item.channel_link, niche: item.niche, platform: item.platform, avg_views: item.avg_views, engagement_rate: item.engagement_rate, stars: creatorScore(item, data.profile.rating_weights), demographics: item.stars_demographics || 0, niche_fit: item.stars_niche || 0, engagement_stars: item.stars_engagement || 0, consistency: item.stars_consistency || 0, priority: item.priority, status: item.pipeline_status, date_contacted: item.date_contacted || "", next_action: item.next_action || "", action_due: item.next_action_date || "", notes: item.notes || "" })), headers: { name: "Name", email: "Email", channel: "Channel", niche: "Niche", platform: "Platform", avg_views: "Avg views", engagement_rate: "Engagement %", stars: "Rating", demographics: "Audience", niche_fit: "Niche fit", engagement_stars: "Engagement stars", consistency: "Consistency", priority: "Priority", status: "Status", date_contacted: "Date contacted", next_action: "Next action", action_due: "Action due", notes: "Notes" } }
          : type === "brands"
            ? { rows: data.brands.map((item) => ({ company: item.name, domain: item.domain, type: item.brand_type, contact_email: item.contact_email, priority: item.priority, status: item.pipeline_status, date_contacted: item.date_contacted || "", next_action: item.next_action || "", action_due: item.next_action_date || "", notes: item.notes || "" })), headers: { company: "Company", domain: "Domain", type: "Type", contact_email: "Email", priority: "Priority", status: "Status", date_contacted: "Date contacted", next_action: "Next action", action_due: "Action due", notes: "Notes" } }
          : type === "contacts"
            ? { rows: data.contacts.map((item) => ({ brand: data.brands.find((brand) => brand.id === item.brand_id)?.name || "", first_name: item.first_name, last_name: item.last_name, title: item.title, email: item.email, linkedin_url: item.linkedin_url, status: item.pipeline_status, date_contacted: item.date_contacted || "", notes: item.notes || "" })), headers: { brand: "Brand", first_name: "First name", last_name: "Last name", title: "Title", email: "Email", linkedin_url: "LinkedIn", status: "Status", date_contacted: "Date contacted", notes: "Notes" } }
            : { rows: data.campaigns.map((item) => ({ name: item.name, brand: data.brands.find((brand) => brand.id === item.brand_id)?.name || "", platform: item.platform, agreed_payment: item.agreed_payment, creator_payout: item.creator_payout, status: item.status, start_date: item.start_date, due_date: item.due_date, notes: item.notes || "" })), headers: { name: "Campaign", brand: "Brand", platform: "Platform", agreed_payment: "Deal value", creator_payout: "Creator payout", status: "Status", start_date: "Start", due_date: "Due", notes: "Notes" } };
    download(`influenceflow-${type}.csv`, toCSV(built.rows, built.headers), "text/csv"); toast(`${type} CSV exported`);
  };

  return <div className="settings-page"><PageHeader eyebrow="Workspace control" title="Settings" description="Manage your identity, reminders, portable data, and local workspace state." />
    <div className="settings-layout"><nav><a href="#profile" onClick={(event) => { event.preventDefault(); document.getElementById("profile")?.scrollIntoView({ behavior: "smooth" }); }}><UserRound /> Profile <ChevronRight /></a><a href="#reminders" onClick={(event) => { event.preventDefault(); document.getElementById("reminders")?.scrollIntoView({ behavior: "smooth" }); }}><Bell /> Reminders <ChevronRight /></a><a href="#scoring" onClick={(event) => { event.preventDefault(); document.getElementById("scoring")?.scrollIntoView({ behavior: "smooth" }); }}><Gauge /> Creator scoring <ChevronRight /></a><a href="#templates" onClick={(event) => { event.preventDefault(); document.getElementById("templates")?.scrollIntoView({ behavior: "smooth" }); }}><FileText /> Email templates <ChevronRight /></a><a href="#data" onClick={(event) => { event.preventDefault(); document.getElementById("data")?.scrollIntoView({ behavior: "smooth" }); }}><Database /> Data & backup <ChevronRight /></a></nav><main>
      <section id="profile" className="settings-section"><div className="settings-heading"><span><UserRound /></span><div><h2>Profile</h2><p>Your private workspace identity and current account.</p></div></div><div className="settings-body"><div className="profile-setting"><Avatar name={name || user?.email || "IF"} size="lg" /><div><Input label="Display name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Your name" /><span>Signed in as {user?.email}</span></div></div><Button onClick={save}><Save size={15} /> Save profile</Button><div style={{ marginTop: 18, paddingTop: 16, borderTop: "1px solid var(--line)", display: "grid", gap: 10 }}><div><strong style={{ fontSize: 13 }}>Change password</strong><p style={{ margin: "4px 0 0", color: "var(--muted)", fontSize: 12 }}>At least 8 characters. You stay signed in on this device.</p></div><Input label="New password" type="password" value={pw1} onChange={(event) => setPw1(event.target.value)} placeholder="At least 8 characters" minLength={8} /><Input label="Confirm password" type="password" value={pw2} onChange={(event) => setPw2(event.target.value)} placeholder="Repeat it" minLength={8} /><div><Button variant="secondary" onClick={changePassword}>Update password</Button></div></div></div></section>
      <section id="reminders" className="settings-section"><div className="settings-heading"><span><Bell /></span><div><h2>Reminder preferences</h2><p>Choose how upcoming meetings should reach you.</p></div></div><div className="settings-body"><div className="reminder-options">{(["browser", "email", "both", "off"] as const).map((option) => <button className={data.profile.reminder_prefs === option ? "selected" : ""} key={option} onClick={() => { data.updateProfile({ reminder_prefs: option }); toast(`Reminders set to ${option}`); }}><span>{option === "browser" ? "Browser" : option === "email" ? "Email" : option === "both" ? "Browser + email" : "Off"}</span><small>{option === "browser" ? "Alerts while the app is open" : option === "email" ? "Requires a configured email function" : option === "both" ? "Use every configured channel" : "No meeting reminders"}</small>{data.profile.reminder_prefs === option && <Check />}</button>)}</div><Button variant="secondary" onClick={async () => { if (!("Notification" in window)) return toast("Notifications unavailable", "error"); const result = await Notification.requestPermission(); toast(`Browser permission: ${result}`, result === "granted" ? "success" : "info"); }}><Bell size={15} /> Test browser permission</Button></div></section>
      <ScoringSettings />
      <TemplateSettings />
      <section id="data" className="settings-section"><div className="settings-heading"><span><Database /></span><div><h2>Data & backup</h2><p>Export everything in versioned formats or import a previous workspace safely.</p></div></div><div className="settings-body"><div className="data-actions"><button onClick={exportBackup}><span><HardDriveDownload /></span><div><strong>JSON backup v2</strong><small>All records, links, settings and activity</small></div><Download /></button><button onClick={() => fileRef.current?.click()}><span><Upload /></span><div><strong>Import backup</strong><small>Validate and preview before changes</small></div><ChevronRight /></button><input ref={fileRef} type="file" accept=".json,application/json" onChange={readBackup} hidden /></div><div className="csv-export-row"><span><FileJson /> CSV exports</span>{(["influencers", "brands", "contacts", "campaigns"] as const).map((type) => <button key={type} onClick={() => exportCollection(type)}>{type}<Download /></button>)}</div>{importError && <div className="import-error"><AlertTriangle /> <span><strong>Backup validation failed</strong>{importError}</span><button onClick={() => fileRef.current?.click()}><RefreshCcw /> Retry</button></div>}<div className="privacy-note"><LockKeyhole /><span><strong>Your exports are generated in the browser.</strong>Keep backup files somewhere private. They can contain contact and campaign details.</span></div></div>      </section>
    </main></div>
    <Modal open={Boolean(preview)} onClose={() => setPreview(null)} title="Backup preview" description="Review the schema and choose how name conflicts should be handled.">{preview && <div className="backup-preview"><div className="backup-counts"><span><b>{preview.creators.length}</b> influencers</span><span><b>{preview.brands.length}</b> brands</span><span><b>{preview.contacts.length}</b> contacts</span><span><b>{preview.campaigns.length}</b> campaigns</span><span><b>{preview.meetings.length}</b> meetings</span><span><b>{(preview.followups || []).length}</b> follow-ups</span></div><Select label="Conflict handling" value={conflictMode} onChange={(event) => setConflictMode(event.target.value)}><option value="skip">Merge and skip matching names</option><option value="keep-both">Merge and keep both</option><option value="replace">Replace current workspace</option></Select><div className="schema-valid"><ShieldCheck /><span><strong>Schema validation passed</strong>Core collections are present. Missing legacy collections were initialized safely.</span></div><div className="modal-actions"><Button variant="ghost" onClick={() => setPreview(null)}>Cancel</Button><Button onClick={importNow}>Import workspace</Button></div></div>}</Modal>
  </div>;
}

const themes: { id: ThemeName; label: string; description: string; note: string }[] = [
  { id: "agency", label: "Agency", description: "Editorial violet, warm paper and deliberate contrast.", note: "Premium default" },
  { id: "light", label: "Light", description: "Bright white space, ink-black type and maximum readability.", note: "Clear & spacious" },
  { id: "dark", label: "Dark", description: "Rich charcoal layers with quiet lavender highlights.", note: "Elegant depth" },
  { id: "honey", label: "Honey", description: "Warm amber surfaces, soft gold light and refined depth.", note: "Warm luxury" },
  { id: "ocean", label: "Ocean", description: "Deep-water blues, calm teal and fluid luminous accents.", note: "Living water" },
];

export function ThemesPage() {
  const data = useData(); const { toast } = useToast(); const apply = (id: ThemeName) => { data.updateProfile({ theme: id }); document.documentElement.dataset.theme = id; toast(`${themes.find((item) => item.id === id)?.label} theme applied`); };
  return <div className="themes-page"><PageHeader eyebrow="Workspace atmosphere" title="Themes" description="Five intentionally designed modes. Switch instantly without changing the way you work." />
    <div className="theme-showcase">{themes.map((theme, index) => <button key={theme.id} onClick={() => apply(theme.id)} className={`theme-preview preview-${theme.id} ${data.profile.theme === theme.id ? "selected" : ""}`}><div className="theme-preview-top"><span>0{index + 1}</span><em>{theme.note}</em>{data.profile.theme === theme.id && <b><Check /> Active</b>}</div><div className="mini-workspace"><div className="mini-side"><i /><i /><i /><i /></div><div className="mini-main"><span /><strong /><div><i /><i /><i /></div><p /><p /></div></div><div className="theme-preview-copy"><h2>{theme.label}</h2><p>{theme.description}</p><span>{data.profile.theme === theme.id ? "Current theme" : "Apply theme"} <ChevronRight /></span></div></button>)}</div>
  </div>;
}

type TrashType = "creator" | "brand" | "campaign";
export function DeletedPage() {
  const data = useData(); const { toast } = useToast(); const [tab, setTab] = useState<TrashType>("creator");
  const groups = { creator: data.creators.filter((item) => item.archived_at), brand: data.brands.filter((item) => item.archived_at), campaign: data.campaigns.filter((item) => item.archived_at) }; const rows = groups[tab]; const count = groups.creator.length + groups.brand.length + groups.campaign.length;
  const empty = () => { if (confirm(`Permanently delete all ${count} archived records? Related links may also be removed. This cannot be undone.`)) { (Object.keys(groups) as TrashType[]).forEach((type) => data.permanentlyDelete(type, groups[type].map((item) => item.id))); toast("Trash emptied"); } };
  return <div className="deleted-page"><PageHeader eyebrow="Unified trash" title="Archive" description="Restore soft-deleted records or permanently remove them when you are certain." actions={count ? <Button variant="danger" onClick={empty}><Trash2 size={15} /> Empty trash</Button> : undefined} /><Tabs active={tab} onChange={(value) => setTab(value as TrashType)} tabs={[{ value: "creator", label: "Influencers", count: groups.creator.length }, { value: "brand", label: "Brands", count: groups.brand.length }, { value: "campaign", label: "Campaigns", count: groups.campaign.length }]} />{!rows.length ? <EmptyState icon="archive" title={`${tab === "creator" ? "Influencer" : tab === "brand" ? "Brand" : "Campaign"} trash is empty`} text="Archived records appear here and can be restored until permanently deleted." /> : <div className="trash-list">{rows.map((item) => <div key={item.id}><span className="trash-icon">{tab === "creator" ? <UserRound /> : tab === "brand" ? <Database /> : <Sparkles />}</span><div><strong>{item.name}</strong><small>Archived {dateLabel(item.archived_at)}</small></div><span className="trash-type">{tab}</span><Button variant="secondary" size="sm" onClick={() => { data.archive(tab, [item.id], true); toast(`${item.name} restored`); }}><RotateCcw size={14} /> Restore</Button><button className="icon-btn danger" onClick={() => { if (confirm(`Permanently delete ${item.name}?`)) { data.permanentlyDelete(tab, [item.id]); toast("Record permanently deleted"); } }}><X size={16} /></button></div>)}</div>}</div>;
}