-- ===========================================================================
-- Creator Discovery (`discover-creators` Edge Function)
-- Run ALL of this in Supabase's SQL Editor BEFORE deploying the function.
--
-- Creates:
--   1. creator_discovery_settings — per-user search config + schedule
--      (time, timezone, on/off, keywords, negatives, filters, keyword rotation)
--   2. searched_channels           — 7-day "already evaluated" cooldown memory
--   3. discovery_runs              — a log of every run (cron or manual)
--   4. RLS policies + an auto-seed trigger for new users
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1) Settings (one row per user)
-- ---------------------------------------------------------------------------
create table if not exists public.creator_discovery_settings (
  id                    bigint  generated by default as identity primary key,
  user_id               uuid    not null unique references auth.users(id) on delete cascade,

  niche                 text    not null default 'Desk Setups & Battlestations',
  platform              text    not null default 'youtube',
  enabled               boolean not null default true,

  -- Schedule
  schedule_time         text    not null default '08:00', -- HH:MM in schedule_timezone
  schedule_timezone     text    not null default 'Etc/UTC', -- IANA name
  last_scheduled_run_date text  null, -- YYYY-MM-DD of the last scheduled run (prevents re-runs)

  -- Quota / search behavior
  max_keywords_per_run  int     not null default 10, -- how many keywords searched each run (capped to pool size so no duplicates per run)
  keyword_cursor        int     not null default 0,  -- rotation pointer into the keyword pool
  cooldown_days         int     not null default 7,  -- skip re-evaluating a channel for N days

  -- Discovery content — Desk Setups & Battlestations defaults (30 keywords, 10 per run = 3-day cycle)
  keywords              text[]  not null default array[
                              'gaming setup','battlestation','desk setup','triple monitor setup',
                              'cable management','dual monitor setup','white gaming setup','rgb setup',
                              'mechanical keyboard setup','gaming room setup','streamer setup',
                              'pc build showcase','study desk setup','productivity desk setup',
                              'minimalist gaming setup','gaming chair setup','cozy gaming setup',
                              'pink gaming setup','desk tour','gaming corner','custom pc setup',
                              'ultrawide monitor setup','standing desk gaming','modded pc build',
                              'home office gaming setup','gaming desk','room tour desk','monitor arm setup',
                              'led strip desk setup','aesthetic desk setup'
                          ],
  negative_kw           text[]  not null default array[
                              'kitchen setup','school desk','stock trading setup','forex setup',
                              'call center setup','dentist office setup','photography studio setup',
                              'wedding setup','camping setup','tattoo studio setup','makeup vanity setup',
                              'aquarium setup','home theater setup','network server setup',
                              'accounting desk','law office setup','baby nursery setup','classroom desk setup'
                          ],
  niche_bio_kw          text[]  not null default array[
                              'gaming setup','battlestation','desk setup','pc setup','setup tour',
                              'workspace','streamer','desk','cable management','keyboard','monitor',
                              'gaming room','gaming pc','rgb','peripherals','desk tour','aesthetic setup'
                          ],

  -- Filters
  subscriber_min        bigint  not null default 50000,
  subscriber_max        bigint  not null default 1000000,
  min_avg_views         bigint  not null default 50000,
  min_engagement_pct    numeric not null default 1,
  max_days_since_upload int     not null default 21,
  min_longform_videos   int     not null default 3,
  max_longform_per_channel int  not null default 12,
  shorts_max_seconds    int     not null default 60,
  target_count          int     not null default 50,

  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 2) Cooldown memory (channels already evaluated this week)
-- ---------------------------------------------------------------------------
create table if not exists public.searched_channels (
  id              bigint generated by default as identity primary key,
  user_id         uuid    not null references auth.users(id) on delete cascade,
  channel_url     text    not null,
  channel_id      text,
  last_searched_at timestamptz not null default now(),
  constraint searched_channels_user_url unique (user_id, channel_url)
);

-- ---------------------------------------------------------------------------
-- 3) Run log
-- ---------------------------------------------------------------------------
create table if not exists public.discovery_runs (
  id                   bigint generated by default as identity primary key,
  user_id              uuid   not null references auth.users(id) on delete cascade,
  trigger              text   not null default 'cron', -- 'cron' | 'manual'
  ran_at               timestamptz not null default now(),
  keywords_searched    int,
  searches_performed   int,
  keyword_pool_total   int,
  channels_found       int,
  channels_skipped_cooldown int,
  channels_dupe_existing    int,
  channels_considered  int,
  shortlisted          int,
  fresh                int,
  inserted             int,
  api_keys_used        int,
  quota_exhausted      boolean not null default false,
  error                text,
  created_at           timestamptz not null default now()
);

create index if not exists discovery_runs_user_ran_idx   on public.discovery_runs   (user_id, ran_at desc);
create index if not exists searched_channels_user_idx    on public.searched_channels (user_id, last_searched_at desc);
-- ---------------------------------------------------------------------------
-- RLS — enable and lock down
-- ---------------------------------------------------------------------------
alter table public.creator_discovery_settings enable row level security;
alter table public.searched_channels            enable row level security;
alter table public.discovery_runs               enable row level security;

-- Users manage their own settings (toggle, time, timezone, keywords, filters)
drop policy if exists "own discovery settings" on public.creator_discovery_settings;
create policy "own discovery settings"
  on public.creator_discovery_settings for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Users can read their own run log (the UI shows last-run status/counts).
-- Inserts/updates are done by the Edge Function via the service role.
drop policy if exists "own discovery runs select" on public.discovery_runs;
create policy "own discovery runs select"
  on public.discovery_runs for select
  using (auth.uid() = user_id);

-- Users can read their own cooldown memory (read-only; written by the function)
drop policy if exists "own searched channels select" on public.searched_channels;
create policy "own searched channels select"
  on public.searched_channels for select
  using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Auto-seed a settings row for every user created from now on
-- (so the function + UI always have config, and the trigger can find the
-- target even without TARGET_USER_ID).
-- ---------------------------------------------------------------------------
create or replace function public.seed_discovery_settings()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.creator_discovery_settings (user_id) values (new.id)
  on conflict (user_id) do nothing;
  return new;
end $$;

drop trigger if exists on_user_created_seed_discovery on auth.users;
create trigger on_user_created_seed_discovery
  after insert on auth.users
  for each row execute function public.seed_discovery_settings();

-- Backfill existing users (run once if you have accounts already):
-- insert into public.creator_discovery_settings (user_id)
--   select id from auth.users
--   on conflict (user_id) do nothing;
--
-- ---------------------------------------------------------------------------
-- DEPLOY + SCHEDULING (run after creating the tables)
-- ---------------------------------------------------------------------------
-- 1) Set secrets (in your Supabase dashboard or CLI):
--      supabase secrets set YOUTUBE_API_KEYS=key1,key2,key3,key4,key5 \
--        DISCOVERY_SECRET=a-long-random-string-you-invent
--    (YOUTUBE_API_KEY also works as a single-key fallback.)
--
-- 2) Deploy the function:
--      supabase functions deploy discover-creators
--
-- 3) Enable extensions (Supabase: Database -> Extensions):
--      pg_cron, pg_net
--
-- 4) Add a 5-minute "tick". The function decides which user's slot is due
--    based on THEIR time + timezone, and only then runs their search. This
--    means changing time/timezone in the Discovery UI takes effect with NO
--    further cron edits. Replace <PROJECT_URL>, <ANON_KEY>, <DISCOVERY_SECRET>.
--
--    select cron.schedule(
--      'influenceflow-discovery-tick',
--      '*/5 * * * *',
--      $$ select net.http_post(
--           url := '<PROJECT_URL>/functions/v1/discover-creators',
--           headers := jsonb_build_object(
--             'Content-Type','application/json',
--             'apikey','<ANON_KEY>',
--             'x-discovery-secret','<DISCOVERY_SECRET>'
--           ),
--           body := '{}'::jsonb
--         ) as request_id;
--      $$
--    );
--
-- Cost: a 5-min tick is effectively a no-op that checks settings (no user is
-- due) except at the scheduled minute, so it's ~8,600 cheap invocations a
-- month, far under the 500k/mo free Edge Function allowance. Your daily run
-- also counts as project activity, so the free DB won't be paused for idling.
--
-- Manual runs: the Discovery UI "Run now" button calls the same function with
-- your login token, so it never needs the secret.
-- ---------------------------------------------------------------------------